### PR TITLE
feat(scss) new utility for flexbox

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
A CSS property that is often applied in a flexbox context, especially for this: https://css-tricks.com/flexbox-truncated-text/

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1288

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1288

**Review by RipripKipkip — APPROVED** [review]

**Review by BertrandPodevin — APPROVED** [review]

**Comment by sanlucca** [comment]
Do we actually need this isolated ? It feels weird, I wonder if it shouldn't be a whole utility for what is it for: flex ellipsis

**Comment by vvalentin-lucca** [comment]
@sanlucca It was an example, but it's not just for that.

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1288

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1288

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1288

**Pull request merged**
