### PR TITLE
[Card] Component focus style 

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Set focus style on card instead of arrow if arrow is focused.

-----

https://github.com/LuccaSA/lucca-front/assets/25581936/23d1ecbd-ee4d-4e8d-98c2-34e640e0d4a7

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2470/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11038/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2470/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11328/ui-diff)

**Review by martincadoux — APPROVED** [review]

**Pull request merged**
