### PR TITLE
enh : improve documentation options readability

### PR DESCRIPTION
**Pull request by BertrandPodevin**
## Description

Improve image selection  readability in emptyState documentation 

**Before :**
image

image

**After :**

image

image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3072/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3072/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/23258/ui-diff)

**Comment by jeremie-lucca** [comment]
Duplicated in https://github.com/LuccaSA/lucca-front/pull/3100 to target `master`

**Pull request closed without merging**
