### PR TITLE
[Popover2] Add option to remove keyboard close button

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Add option to remove keyboard close button + apply it to multilanguage

-----

### CODE REVIEW

**Review by Supamiu — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3027/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21807/ui-diff)

**Comment by jeremie-lucca** [comment]
Cherry picked from @Supamiu 's work

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3027/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21809/ui-diff)

**Pull request merged**
