### PR TITLE
[Toast] UI refactor

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Toast UI refactor

-----

ℹ️ Toast timer & removal is historically handled by CSS animation. It works well, but a timer refactor would be way cleaner. 

image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2841/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17930/ui-diff)

**Review by vvalentin-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2841/storybook

**Review by Supamiu — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18199/ui-diff)

**Pull request merged**
