### PR TITLE
[ref] unitless lineheight

### PR DESCRIPTION
**Pull request by jeremie-lucca**

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://260-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://260-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://260-pr-lucca-front-LuccaSA.surge.sh

**Comment by jefBinomed** [comment]
@jeremie-lucca there is some conflicts

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://260-pr-lucca-front-LuccaSA.surge.sh

**Pull request merged**
