### PR TITLE
Button cleanup

### LINKED ISSUE #1779: button component do not use is own state mixin
The are 2 problems with the states (`hover`, `active`, `focus`...) management of the `button` component in LF10 :

- They are duplicated in `button > component` and in `button > states > state` (wich isn't used anywhere). 
- The `state`  mixin seems to be bugged with a `background-color !important;`

We should remove the states management from `button > component`, fix the `button > states > state` mixin and use it instead.

### LINKED ISSUE #1880: [Button] states management specificity is too high
Button states rules selectors are writen this way :
```
.button:not([disabled],.is-disabled):state {...}
```
This selector specifity is too high, imparing our capability to override it properly.

The disabled state should rather be managed apart, to keep normal button states clean :
`.button:state {...}`
and
`.button:[disabled]:state,.button.is-disabled:state {...}`

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

- [x] Strict separation between modifiers and states.
- [x] Overloaded values all passed in CSS variables. 
- [x] Remove all `!important`.
- [x] Remove all `:not(:disabled)`.

fix #1779 
fix #1880 

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12299/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12304/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Review by jeremie-lucca — CHANGES_REQUESTED** [review]
We have hover specificity issues on `mod-inverted` & `<a>` buttons : 
image

What about removing the right margin and replacing it by a CSSvar to let teams switch whenever they want?

**Comment by vvalentin-lucca** [comment]
@jeremie-lucca `--components-button-margin`?

**Comment by jeremie-lucca** [comment]
@vvalentin-lucca Yep, my suggestion is to set it at 0, so we could get rid of these annoying right margins in standard flex usage and provide a snippet in changelog to let product teams keep this margin if they want / avoid breakings.

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12357/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12365/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12370/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12372/ui-diff)

**Review by jeremie-lucca — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12377/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12385/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2534/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
