### PR TITLE
[NG] Handle disabled state on select and popover

### PR DESCRIPTION
**Pull request by GuillaumeNury**

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://337-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
@GuillaumeNury changelog ([this one](https://github.com/LuccaSA/lucca-front/blob/handle.disabled.select/packages/ng/CHANGELOG.md))

**Comment by GuillaumeNury** [comment]
@lucienbertin done

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://337-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://337-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
fixed in v2.0

**Pull request closed without merging**
