### PR TITLE
feat(scss) utilities for hx

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
- Utilities styles for .u-h1… .u-h6 ;
- rework on sections ;
- linter ok.

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1269

**Review by lucienbertin — APPROVED** [review]
still seems ok to me

**Review by sanlucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1269

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1269

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1269

**Pull request merged**
