### PR TITLE
feat(scss) Breadcrumbs

### LINKED ISSUE #976: revision style for breadcrumb
https://www.figma.com/file/kqPaSqundLaO0v993cjRDe/UI-Styleguide-1.0-Master-Components?node-id=120%3A16

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
- New styles.
- Works with links and buttons.
- With aria for current page.
- With `.mod-compact`.
- Closes #976.

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1127

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1127

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1127

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1127

**Pull request merged**
