### PR TITLE
Fix.16.2

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

- Tag : Small by default
- Group of buttons : Fix border radius
- Filter : Keep boxshadow instead of border + fix padding + fix clearer position
- Sidenav : Remove secondary ref
- Datepicker : Fix textfield style + fix paddings

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2163/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4468/ui-diff)

**Review by almonais — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2163/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4515/ui-diff)

**Review by almonais — APPROVED** [review]

**Pull request merged**
