### PR TITLE
Bunch of Simple Select features

### PR DESCRIPTION
**Pull request by GuillaumeNury**
## Description

* ✨ Disabled options
* ✨ API V3 support
* ✨ API V4 support
* 🌐 Translations
* 📖 [New documentation](http://lucca-front.lucca.local/PR-2040/storybook/?path=/docs/documentation-forms-simpleselect--docs)
* 🐛 Selected option was not selected when options are asynchronous

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2040/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2040/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2040/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2040/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2040/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2040/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2040/storybook

**Comment by GuillaumeNury** [comment]
@3htomit @F2X I keep luOption naming at the moment. When the multi-select will land, we will have to make some choices. I prefer to wait next PR

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
