### PR TITLE
Utils for content

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

New utilities.

-----

```css
.u-width100\% {
  width: 100% !important;
}

.u-widthFitContent {
  width: fit-content !important;
}

.u-height100\% {
  height: 100% !important;
}

.u-heightFitContent {
  height: fit-content !important;
}

.u-minWidth0 {
  min-width: 0 !important;
}

.u-minHeight0 {
  min-height: 0 !important;
}
```

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2347/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7828/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2347/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/8350/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
