### PR TITLE
[dropdown] divider

### LINKED ISSUE #2061: [Dropdown option] Separator
Add dropdown option separator mod.
https://lucca.slack.com/archives/GSCU69USV/p1680077632963399
image_720

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Fixes #2061 

-----

-----

Capture d’écran 2024-12-06 à 15 31 46

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3267/storybook

**Comment by AlexiaAlarza** [comment]
Oh it's because it's also changed in Figma ?

**Comment by vvalentin-lucca** [comment]
@AlexiaAlarza I've added `Optional` to avoid this potential misunderstanding.

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3267/storybook

**Review by AlexiaAlarza — DISMISSED** [review]

**Comment by jeremie-lucca** [comment]
@vvalentin-lucca In my opinion `optional` should only apply to elements wrapped into 2 elements.
We created this convention to avoid DOM misunderstandings, but if we apply `optional` to this one, we should also apply it on a very large amount of elements as components options create a huge variety on DOM.

**Review by jeremie-lucca — CHANGES_REQUESTED** [review]
@vvalentin-lucca In my opinion optional should only apply to elements wrapped into 2 elements.
We created this convention to avoid DOM misunderstandings, but if we apply optional to this one, we should also apply it on a very large amount of elements as components options create a huge variety on DOM.

**Comment by vvalentin-lucca** [comment]
OK, so I've removed the optional, but I haven't put the separator between all the elements.

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3267/storybook

**Comment by jeremie-lucca** [comment]
Thanks, we could alway display multiple stories if this is still unclear 🙂

**Review by jeremie-lucca — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
