### PR TITLE
docs(tooltip): story refactor

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Improved tooltip story format and code example.

-----

-----

### CODE REVIEW

**Review by vvalentin-lucca — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2867/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2867/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18471/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18473/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
