### PR TITLE
[fix] [label] .mod-icon position

### PR DESCRIPTION
**Pull request by RipripKipkip**
## Description

label.mod-icon changes position when you alternate the position of the icon

-----

- [x] padding
- [x] sizes
- [x] align text icon

Before
image
After
image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Review by almonais — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Review by jeremie-lucca — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1937/storybook

**Review by F2X — APPROVED** [review]

**Review by almonais — APPROVED** [review]

**Pull request merged**
