### PR TITLE
[3.0] SidePanel styles + overlay animations

### PR DESCRIPTION
**Pull request by sanlucca**
Adds sidepanel styles and basic overlay animations using CSS.
I opted for CSS animations rather than Angular Animations due to the complexity of implementing and overriding Angular ones.

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://670-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://670-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
the leaving animations is maybe a bit too long, the overlay seems to remain .25s after the popup/modal/sp disappeared

popup-leave

**Comment by sanlucca** [comment]
> the leaving animations is maybe a bit too long, the overlay seems to remain .25s after the popup/modal/sp disappeared
> 
> popup-leave

Weird, I didn't have that yesterday. I'm fixing it

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://670-pr-lucca-front-LuccaSA.surge.sh

**Pull request merged**
