### PR TITLE
Link icon with no wrap before icon

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

-----

-----

Capture d’écran 2024-01-22 à 18 01 24

### CODE REVIEW

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12183/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2525/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12326/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2525/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12354/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
