### PR TITLE
Select fixes and refacto

### PR DESCRIPTION
**Pull request by GuillaumeNury**
## Description

Fixes:

* no more double call when opening a select with a "clue" while closed
* no more jump back to the first option when options change
* "Empty" result was not displayed when not using `[loading]` input
* NullRefEx when pending options
* `(nexyPage)` was not triggered on multi-select when navigating using keyboard
* broken "With pagination" stories

Refactos:

* `SimpleSelectApiV3Directive` / `SimpleSelectApiV4Directive` / `ALuSimpleSelectApiDirective` in `@lucca-front/ng/simple-select/api` are deprecated in favor of `CoreSelectApiV3Directive` / `CoreSelectApiV4Directive` / `ALuCoreSelectApiDirective ` in `@lucca-front/ng/core-select/api` as it is used on both simple and multi selects
* Remove `MULTI_SELECT_PANEL_DATA` and `SIMPLE_SELECT_PANEL_DATA` as they were useless abstractions. Panel knows its input directly

-----

Optionally, technical or more in-depth description for reviewers.
Keep an empty line under your text, as well as the 5 lines that follow it.

-----

### CODE REVIEW

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12671/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2547/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12696/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2547/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12703/ui-diff)

**Review by Supamiu — DISMISSED** [review]

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2547/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12889/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
