### PR TITLE
Improve stories displayed code

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Improve stories displayed code

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2195/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5121/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2195/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5123/ui-diff)

**Review by almonais — APPROVED** [review]

**Review by shajz — APPROVED** [review]

**Pull request merged**
