### PR TITLE
Css var for content icon

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Css var for content icon.

-----

-----
Capture d’écran 2024-02-27 à 17 40 33
Capture d’écran 2024-02-27 à 16 30 18

Capture d’écran 2024-02-27 à 16 30 46
Capture d’écran 2024-02-27 à 16 31 44

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2595/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13857/ui-diff)

**Comment by BertrandPodevin** [comment]
Great ! Not directly linked to thoses changes but `".lucca-icon .icon-"` is repeated one time for each icon in the output css. That's 525 times !
I wonder if we could reduce this bloat with a small (breaking) change like renaming every use with ".lu-icon-xxxxx"

**Review by BertrandPodevin — DISMISSED** [review]

**Comment by vvalentin-lucca** [comment]
@BertrandPodevin I've thought about it too, but I'm afraid I'd affect the selector's specificity.

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2595/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13873/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
