### PR TITLE
1962 toasts add title option

### PR DESCRIPTION
**Pull request by g-drouard**
## Description

- Add optional title on toast
- Improve toast display

-----

- Add optional parameter `title` on `LuToasInput`
- Changed toast graphics rendering to best match Figma components

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1971/storybook

**Comment by vvalentin-lucca** [comment]
Why not use innerHTML to pass the HTML structure you want (including the title) ?

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1971/storybook

**Comment by g-drouard** [comment]
> Why not use innerHTML to pass the HTML structure you want (including the title) ?

Good point, the reasons I see:
- Match Figma variant toast with title
- Make calls for the toast service clearer and more concise
- Allow to have two different translation keys between the title and the message to manage identical titles on toasts for example

**Review by GuillaumeNury — APPROVED** [review]
LGTM

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
