### PR TITLE
User Popover : adjustments + HTML story

### LINKED ISSUE #2783: [User popover] Date format
- ~~Year should not be displayed~~ ☑
- Month should be abbreviated using 4 characters max (e.g. Sept., May) and year removed
- ~~Text color should be Neutral 800/600 instead of 700 everywhere~~ ☑
- ~~(Bonus) Allow last line to line break to avoid issues on wordy languages like german~~ ☑

LF
capture_d___e__cran_2024-05-06_a___18 18 10_360

Figma
image

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Fix #2783 

 ⚠️ For the time being, the year remains in long format.

- [x] A story has been added in HTML format.
- [x] Text colors have been corrected.
- [x] The component has been slightly simplified (no more mod-link, no more width calculation, color inheritance).
- [x] Long text management has been switched to HTML, and deactivated on the last part.

-----

-----

Capture d’écran 2024-05-23 à 15 53 10

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2812/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17328/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2812/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17336/ui-diff)

**Review by Supamiu — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
