### PR TITLE
For.options

### PR DESCRIPTION
**Pull request by lucienbertin**
add directive `luForOtiopns` so i can write this
```html
<lu-option-picker>
  <any-feeder></any-feeder>
  <lu-option *luForOptions="let option" [value]="option">{{ option.name }}</lu-option>
</lu-option-picker>
```

### CODE REVIEW

**Comment by lucienbertin** [comment]
@sanlucca do i completely remove the `lu-options` component ? and rewrite all with `*luForOptions` ?

**Comment by sanlucca** [comment]
Yes, lu-options makes no sense anymore

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://373-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://373-pr-lucca-front-LuccaSA.surge.sh

**Pull request merged**
