### PR TITLE
[19.1] Fix conflicts

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Fix conflicts

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3287/storybook

**Review by GuillaumeNury — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3287/storybook

**Review by vvalentin-lucca — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3287/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3287/storybook

**Review by GuillaumeNury — APPROVED** [review]

**Review by vvalentin-lucca — APPROVED** [review]

**Pull request merged**
