### PR TITLE
feat(scss) Timelines

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
image

image

image

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Comment by BertrandPodevin** [comment]
Great component ! A question : why do you use intermediate aria-hidden `li` between steps for the gauge ? Is there an accessibility reason ?

Wouldn't it be simpler to just use `li` for steps only, pseudo-elements for gauge and clever uses of `align-items: space-between` and `flex-grow` for the horizontal version, and position: absolute for the vertical version ?

Why does the vertical timeline is not an `ol` ?

**Comment by vvalentin-lucca** [comment]
> Why do you use intermediate aria-hidden `li` between steps for the gauge ? Is there an accessibility reason ?
> Wouldn't it be simpler to just use `li` for steps only, pseudo-elements for gauge and clever uses of `align-items: space-between` and `flex-grow` for the horizontal version, and `position: absolute` for the vertical version ?

I couldn't find how to place an item between two items without adding an extra container.
(And indeed, I am then forced to remove it semantically.)

Would you have a solution for that? https://codepen.io/vincent-valentin/pen/eYZVEvd
 
> Why does the vertical timeline is not an `ol` ?

It is sometimes difficult to know when it is appropriate to use lists (ordered or not).
For a number of steps, it seems relevant but for paragraphs or more consequent contents, I find that we go beyond the principle of enumeration.
Without the associated style, it would not seem clever to me to put an `ol` around a series of paragraphs.

Nevertheless, note that if it is not presented in the examples, there is nothing to prevent it, and the code will continue to work.

**Comment by BertrandPodevin** [comment]
Here's a possible solution that does not use extra container for the gauge : https://codepen.io/bertrandpodevin/pen/rNeJzgG

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Review by BertrandPodevin — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Review by sanlucca — COMMENTED** [review]
If you make a mod-vertical with a title only, you lose the gauges. 
image 
I'm wondering if it might come as an issue

**Comment by vvalentin-lucca** [comment]
@sanlucca I'd say yes, I'll see what I can do about it.

**Comment by vvalentin-lucca** [comment]
@sanlucca 
image

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1120

**Pull request merged**
