### PR TITLE
Transparent background for outlined tags

### LINKED ISSUE #2606: [Tags] Outlined background color
Outlined tags should have transparent background color instead of white. 

Figma
image

LF 
image

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Closes #2606 

-----

-----

Capture d’écran 2024-02-28 à 16 35 53

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2607/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13918/ui-diff)

**Review by fbasmaison-lucca — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2607/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13938/ui-diff)

**Pull request merged**
