### PR TITLE
LF 8.1

### PR DESCRIPTION
**Pull request by shajz**
## :tada: Features
- [Button groups] Responsiveness coverage #1544 
## :boom: Breaking changes
- [Timeline] Component harmonization between Figma & LF #1349
	- Removing intermediate size
	- Adding small size / mod-icon
	- Fixing previous, curent, next bullets UI
## :art: Visual changes
- [Tabs bar] Component harmonization between Figma & LF #1356
	- Adding small mod and borderless mod
	- Adding disabled state
	- Fixing fonts, colors, spacings
- [Headings] Fixing line-height #1476 
- [Links] Color management refactor (Primary color is now default) #1337 
- [Selects] Palettes coverage for placeholders, icons and input clearer #1536 
- [Icons] Update warning icon #1545 
## :busts_in_silhouette: Accessibility
- Supports aria-required for mandatory inputs #1541 
- [Modal] Improve close button accessibility (Tooltip, translate hidden message...) #1532 
## :ambulance: Fixes
- [Modal] Fixing issues on touch devices / Adding close cross focus #1459
## :heart: Quick win
- [Icons] Adding icons pause / stop / divide / unarchive / crown #1492 #1534 #1535 
- [Header] Adding mod no-shadow #1526 
## :hammer: Technical
- [Palettes] Using Lucca's default theme on palettes for Prisme purpose #1510 
- [LuApiPagedSearcher] API V4 sorting #1512 
- Removing unused CSS selectors #1533 
- [Lint] Installed eslint and handle generics
  - ⚠️ You may encounter some errors when extending or overriding components which use generics, like ALuOptionOperator. We removed all `<T = any>` types with `<T>`. If you encounter any errors like this when linting your code, you will need to specify the types used by your component.

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1546

**Review by jeremie-lucca — APPROVED** [review]

**Review by GuillaumeNury — APPROVED** [review]

**Pull request merged**
