### PR TITLE
fix(lu-select): panel position not updating when options change

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

`lu-select` wasn't updating when options arrived after the panel has been opened, this PR fixes that issue.

It's also affecting (and fixing) custom selects like `lu-establishment-picker` etc.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2764/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/16570/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2764/storybook

**Comment by jeremie-lucca** [comment]
It works fine on luSelect but seems to fail on Departement which is based on luSelect: 
image

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2764/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/16690/ui-diff)

**Review by shajz — APPROVED** [review]
LGTM

**Pull request merged**
