### PR TITLE
Radiofield

### LINKED ISSUE #2254: [Forms v2] Wrap new fields components
- [ ] Text field
- [ ] Radio field
- [ ] Checkbox field
- [ ] Switch field

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

fix #2254 

-----

-----

Capture d’écran 2024-01-04 à 09 33 55

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2482/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11397/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2482/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2482/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11617/ui-diff)

**Pull request merged**
