### PR TITLE
Status Badge

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

New component : Status badge

-----

image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2057/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2057/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2057/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2057/storybook

**Review by vvalentin-lucca — APPROVED** [review]

**Comment by GuillaumeNury** [comment]
closes #1958

**Pull request merged**
