### PR TITLE
LF 8.2

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## :tada: Features
- [Toast] Toast is now covered by an [Angular component](https://lucca-front.lucca.io/storybook/?path=/docs/documentation-overlays-toasts--basic) (Sass is still supported) #1563
- [Page titles] LF now supports page titles, see https://github.com/LuccaSA/lucca-front/blob/rc/packages/ng/title/README.md for a quickstart guide (spoilers: it's easy) #1650
## :boom: Breaking changes
- [Table of Content / Anchors] Component gets new UI / DOM #1613
  - [New DOM to apply](https://lucca-front.lucca.io/storybook/?path=/docs/documentation-navigation-tableofcontent-basic--basic)
## :art: Visual changes
- [Callout] Text is now grey to improve readability #1572 #1633
- [Button] Size small has now a height of 32px instead of 36px  #1642
- [Checkbox] UI harmonization with design guidelines (Icon size, states...) #1611
  - In order to reduce the dist weight, checkbox doesn't supports `.palette-xxx` anymore.
  - If you use a different color than your primary by default, you need to override your component `default-palette` attribute in `_checkbox.theme.scss`
  - If you use grey checkbox (legacy), you need to replace `.palette-grey` by `.mod-grey`
- [Radio] UI harmonization with design guidelines (Icon size, states...) #1604
  - In order to reduce the dist weight, checkbox doesn't supports `.palette-xxx` anymore.
  - If you use a different color than your primary by default, you need to override your component `default-palette` attribute in _radio.theme.scss
- [Switch] UI harmonization with design guidelines (icons, colors...) #1601
  - Switch color is now overridable and primary by default. If you use a different color than your primary by default, you need to override your component `default-palette` attribute in `_switch.theme.scss`
- [Action Icon] UI harmonization with design guidelines #1607
  - In order to reduce the dist weight, Action Icons doesn't supports `.palette-xxx` anymore.
  - If you use a different color than your primary by default, you need to override your component `default-palette` attribute in `_action-icon.theme.scss`
  - Default size is now 40x40px, you will need to apply a .mod-small for a 32x32px size.
  - A new class `.mod-delete` now covers red coloring
- [Radio Buttons] UI harmonization with design guidelines #1606
  - In order to reduce the dist weight, Radio Buttons doesn't supports `.palette-xxx` anymore.
  - If you use a different color than grey for button style by default, you need to override your component `default-palette` attribute in `_radio-buttons.theme.scss`
  - If you use a different color than primary for hovering style by default, you need to override your component `hover-palette` attribute in `_radio-buttons.theme.scss`
- [Menu] UI harmonization with design guidelines (counter size & color) #1605
  - Primary color can be overrided in `_menu.theme.scss`
  - Now also supports `<button>` element for navigation
  - `.size-small` on `.label.mod-number` should be replaced by `.mod-small`
- [Tags & Labels] Increase contrast for readability #1600
## :busts_in_silhouette: Accessibility
- [Table] Fix keyboard support for table actions #1557
- Add type=button to every buttons #1566
## :heart: Quick win
- [Icons] Add icon-cancel icon #1614
- [Button] `.mod-link` is replaced by `.mod-text` to avoid components confusion. `.mod-link` is still supported for now but considered as legacy. #1435
- [Timeline] Supports 100% width for specific content cases, like cards, in vertical display #1644 
## :hammer: Technical
- Update rxjs from v6 to v7 #1635

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1643

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1643

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1643

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1643

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1643

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1643

**Review by shajz — APPROVED** [review]

**Review by vvalentin-lucca — APPROVED** [review]

**Pull request merged**
