### PR TITLE
Fix ng- states

### PR DESCRIPTION
**Pull request by vvalentin-lucca**

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1159

**Review by lucienbertin — COMMENTED** [review]
without touching the ng part of the coin

when i do combinations of `textfield is-invalid/is-error` and `textfield-input is-invalid/is-error` i get different results

```html
	<form action="#" class="form mod-framed">
		<fieldset class="form-group">
			<legend class="form-group-legend">Col</legend>
			<div class="form-group-line">
				<div class="form-group-line-col">
					<label class="textfield is-invalid">
						<input class="textfield-input is-invalid" placeholder="input invalid" type="text">
						<span class="textfield-label">field invalid</span>
					</label>
				</div>
				<div class="form-group-line-col ">
					<label class="textfield is-error">
						<input class="textfield-input is-invalid" placeholder="input invalid" type="text">
						<span class="textfield-label">field error</span>
					</label>
				</div>
			</div>
			<div class="form-group-line">
				<div class="form-group-line-col">
					<label class="textfield is-invalid">
						<input class="textfield-input" placeholder="input normal" type="text">
						<span class="textfield-label">field invalid</span>
					</label>
				</div>
				<div class="form-group-line-col ">
					<label class="textfield is-error">
						<input class="textfield-input" placeholder="input normal" type="text">
						<span class="textfield-label">field error</span>
					</label>
				</div>
			</div>
			<div class="form-group-line">
				<div class="form-group-line-col">
					<label class="textfield">
						<input class="textfield-input is-invalid" placeholder="input invalid" type="text">
						<span class="textfield-label">field normal</span>
					</label>
				</div>
				<div class="form-group-line-col ">
					<label class="textfield">
						<input class="textfield-input is-error" placeholder="input error" type="text">
						<span class="textfield-label">field normal</span>
					</label>
				</div>
			</div>
```
image

the `is-error` state seems to be the bestest most good but i'm a bit abivalent regarding the change of naming system

**Comment by lucienbertin** [comment]
my bad, i am living in the past

image

**Comment by lucienbertin** [comment]
first bug, i added a `required` in a formly thingamajig and the field appears red at init, without being touched

image

and when i touch it, the red border appears

image

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1159

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1159

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1159

**Pull request merged**
