### PR TITLE
[Timeline] Button coverage

### PR DESCRIPTION
**Pull request by jeremie-lucca**
Allow to use button as timeline action.

### CODE REVIEW

**Review by vvalentin-lucca — DISMISSED** [review]

**Comment by BertrandPodevin** [comment]
@jeremie-lucca when disabled, the button  still has a `text-decoration: underline;` on `hover` (+ `focus`). I think it should not be the case

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1625

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1625

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1625

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1625

**Comment by jeremie-lucca** [comment]
New PR targeting Master : https://github.com/LuccaSA/lucca-front/pull/1631

**Pull request closed without merging**
