### PR TITLE
Add feature table align right

### PR DESCRIPTION
**Pull request by almonais**
image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://677-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://677-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://677-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
english ! @sanlucca

**Pull request merged**
