### PR TITLE
[Components V3] Mobile header

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

New component : Mobile Header

-----

image
image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2152/storybook

**Review by RipripKipkip — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2152/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2152/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5082/ui-diff)

**Review by RipripKipkip — APPROVED** [review]

**Pull request merged**
