### PR TITLE
fix(button): fix compilation error when using luButton without a value

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Fix the issue with `<button luButton></button>` throwing a compilation error due to unsupported default value for the input.

-----
-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2414/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/9596/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2414/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/9599/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Pull request merged**
