### PR TITLE
WIP feat(icon) SVG

### PR DESCRIPTION
**Pull request by vvalentin-lucca**

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1319

**Review by RipripKipkip — APPROVED** [review]

**Comment by shajz** [comment]
This needs a rebase on `rc` because of https://github.com/LuccaSA/lucca-front/pull/1908 but this PR is so old :/
Leaving it to you @vvalentin-lucca

**Comment by jeremie-lucca** [comment]
I'm closing it as it's open since 2021. We could open it again if needed.

**Pull request closed without merging**
