### PR TITLE
@root param for components

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

We can now override the behaviour of @at-root in tables.
Example `@include table.component($atRoot: 'with: rule media')`

Co-authored with @audreylemercier and @jeremie-lucca.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1963/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1963/storybook

**Review by audreylemercier — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1963/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1963/storybook

**Review by BertrandPodevin — DISMISSED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1963/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
