### PR TITLE
[lu-user-tile] [lu-user-picture]: support LU_DEFAULT_DISPLAY_POLICY for picture initials

### PR DESCRIPTION
**Pull request by g-drouard**
## Description

`lu-user-tile` : default initials format is from `LU_DEFAULT_DISPLAY_POLICY` instead of `LuDisplayInitials.firstlast`
`lu-user-picture` : default initials format is from `LU_DEFAULT_DISPLAY_POLICY` instead of `LuDisplayInitials.lastfirst`

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2887/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18652/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2887/storybook

**Review by GuillaumeNury — APPROVED** [review]

**Review by GuillaumeNury — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2887/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18812/ui-diff)

**Pull request merged**
