### PR TITLE
[NG] Extract styles into style mixins

### PR DESCRIPTION
**Pull request by sanlucca**
Extract component embedded style into ng/style folder to allow extension to pickup their parent style easily.
We use mixins rather than placeholders to allow definition without any CSS selectors

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://378-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
im looking for a better name than style-mixins

**Comment by lucienbertin** [comment]
opting for `definition`

©️ anais pieropan 2018

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://378-pr-lucca-front-LuccaSA.surge.sh

**Pull request merged**
