### PR TITLE
[viewTabs] mod-vertical

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
To do :

- [x] talk with the design
- [ ] propose a default breakpoint?
- [ ] switch to the new responsive syntax?

-----

-----

Before:
Capture d’écran 2024-08-23 à 12 25 53

After:
Capture d’écran 2024-08-23 à 12 25 45

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3035/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3035/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21968/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21969/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3035/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/22458/ui-diff)

**Pull request closed without merging**
