### PR TITLE
Icons.452.517

### PR DESCRIPTION
**Pull request by jeremie-lucca**

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://519-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://519-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://519-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
pr remade with #524

**Pull request closed without merging**
