### PR TITLE
[dialog] Internal scroll

### LINKED ISSUE #2977: [Dialog] Move scroll to content
It was decided that scrollbar should be on content instead of full dialog to avoid ugly UI on Windows.
We don't have much confidence toward breakings, so it should be heavily tested before merging.

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Fixes #2977 

-----

-----

Before:
Capture d’écran 2024-09-11 à 12 39 51

After:
Capture d’écran 2024-09-11 à 12 41 50

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3071/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/22628/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3071/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/22632/ui-diff)

**Review by MarcFairbrother — COMMENTED** [review]
Doesn't the html template of the component need to be updated? I can only see updates for the story templates in this PR but it might not be necessary for the ng components.

**Comment by vvalentin-lucca** [comment]
@MarcFairbrother It's just to align the html of the angular version and the static version.

**Review by MarcFairbrother — DISMISSED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3071/storybook

**Pull request merged**
