### PR TITLE
Select.support.multiple

### PR DESCRIPTION
**Pull request by lucienbertin**
- [x] added property multiple to select, picker, displayer
- [x] added `@input multiple` on `lu-select`
- [x] select passes it to its picker
- [x] select multiple + displayer single
- [x] select multiple + displayer multiple
- [x] option-picker multiple handles selection
- [x] option-picker adds `is-selected` to all selected options
- [x] demo
- [x] picker - dont close on selection
- [x] picker - add class `mod-multiple` to picker panel

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://371-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://371-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://371-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
@sanlucca for a displauer multiple, the synthax is

`<ng-container *luDisplayer="let values; multiple: true">{{values?.length}} colors</ng-container>`
or
```html
			<ng-template luDisplayer multiple let-values>
				{{values?.length}} colors
			</ng-template>
```

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://371-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://371-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://371-pr-lucca-front-LuccaSA.surge.sh

**Pull request merged**
