### PR TITLE
feat: move all translations to Lokalise

### PR DESCRIPTION
**Pull request by GuillaumeNury**
## Description

Move all translations to Lokalise, but keep the current DI system so translations are still overridable.
Maybe we can fill all empty translations on Lokalise before releasing this PR.

As a positive side-effect, we now use the same fallbacks as Lucca applications.

-----

Optionally, technical or more in-depth description for reviewers.
Keep an empty line under your text, as well as the 5 lines that follow it.

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2919/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19325/ui-diff)

**Comment by Supamiu** [comment]
We should probably update https://github.com/LuccaSA/lucca-front/blob/rc/packages/ng/core/translate/translation.model.ts too?

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2919/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19354/ui-diff)

**Review by Supamiu — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2919/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19361/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2919/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19383/ui-diff)

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2919/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19386/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Review by Supamiu — APPROVED** [review]

**Pull request merged**
