### PR TITLE
LF 16.2

### PR DESCRIPTION
**Pull request by jeremie-lucca**
### 🎉 Features
- Grid component was rewritten, based on a display grid, in order to reduce component weight and cover further form guidelines. https://github.com/LuccaSA/lucca-front/pull/2133
  - To keep using the deprecated version, you can replace CSS import `@forward '@lucca-front/scss/src/components/grid'` by `@forward '@lucca-front/scss/src/components/gridLegacy'`
- [Status badge] Adding large variation https://github.com/LuccaSA/lucca-front/pull/2165
 
### 🎨 Visual changes
- Update components UI (batch 2)
  - Timeline https://github.com/LuccaSA/lucca-front/pull/2151 
  - File upload https://github.com/LuccaSA/lucca-front/pull/2147
  - Card https://github.com/LuccaSA/lucca-front/pull/2146
  - Table https://github.com/LuccaSA/lucca-front/pull/2145
  - List https://github.com/LuccaSA/lucca-front/pull/2143
  - Primary menu (sidenav) https://github.com/LuccaSA/lucca-front/pull/2142
  - Loading https://github.com/LuccaSA/lucca-front/pull/2141
  - Dropdown https://github.com/LuccaSA/lucca-front/pull/2140
   - 💥 To get the gap between the options, you will need to nest `lu-select-option` instances inside a `.lu-picker-content-options` parent. 
  - Calendar https://github.com/LuccaSA/lucca-front/pull/2139
  - Chip, Tag, Tooltip, Menu, Page header, Timepicker, Pagination, Popover, Filter https://github.com/LuccaSA/lucca-front/pull/2138
 - [Status Badge] Update colors https://github.com/LuccaSA/lucca-front/pull/2165

### 🔨 Technical
- [Chip] Improve cross icon position https://github.com/LuccaSA/lucca-front/pull/2123
- Remplace deprecated CSS elevation vars by boxShadow https://github.com/LuccaSA/lucca-front/pull/2156
- Fix vulnerabilities https://github.com/LuccaSA/lucca-front/pull/2154
-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2159/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4236/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2159/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4269/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2159/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4483/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2159/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4517/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2159/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4528/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4545/ui-diff)

**Review by shajz — APPROVED** [review]

**Review by vvalentin-lucca — APPROVED** [review]

**Pull request merged**
