### PR TITLE
fix(ng/user): MeOption blank

### LINKED ISSUE #1501: Me option is blank
If options are loaded before MeOption, Me is blank

Observed
image

Expected
image

### PR DESCRIPTION
**Pull request by guillerot**
### Fixed issues
- [fix #1501](https://github.com/LuccaSA/lucca-front/issues/1501) - me option is blank

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1502

**Review by GuillaumeNury — APPROVED** [review]
Thx 😃

**Comment by GuillaumeNury** [comment]
Fixes #1501

**Review by lucienbertin — APPROVED** [review]

**Comment by shajz** [comment]
It was fixed in https://github.com/LuccaSA/lucca-front/pull/1453 sorry for the long wait before merge !
Thanks for fixing it though :)

**Pull request closed without merging**
