### PR TITLE
docs(radio-input): add base usage docs

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Add usage docs for the new radio input wrapper

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2922/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19350/ui-diff)

**Review by jeremie-lucca — DISMISSED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2922/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21247/ui-diff)

**Pull request merged**
