### PR TITLE
New framed form

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
News: 

- new styles with double border in focus;
- new function for fake border;
- implicits `label`;
- `textarea` can be resized (with a min. and max. height);
- columns can be done automatically;
- `fieldset/legend` for titles (more accessible);
- inline `radio/checkbox` inherited from the dedicated components (without additional overload);
- `radio/checkbox` in a `fieldset/legend` when necessary;
- `disabled `possible on `radio/checkbox`;
- `required `possible on `radio/checkbox` (with `aria-required` for a11y);
- states (success, warning, error) possible on the `radio/checkbox` ;
- suffix possible (**but** without absolute guarantee on overlaps);
- field overlays possible (top and bottom);
- loading on `radio/checkbox`;
- `focus-within` for overlays.

Limitations:

- suffix + loading;
- suffix + search; 
- overlay + `radio/checkbox`

Still to do:

- formly;
- states with `is-valid/invalid/disabled/readonly`;
- better arrangement of the code.

---

image

---

image

---

image

---

image

---

image

---

image

---

image

---

image

---

image

---

image

### CODE REVIEW

**Comment by lucienbertin** [comment]
shouldn't this go toward `rc` and not `master` ?

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1106

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1106

**Comment by vvalentin-lucca** [comment]
https://github.com/LuccaSA/lucca-front/pull/1115

**Pull request closed without merging**
