### PR TITLE
Add neutral 400 for rgb colors

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Sorry for the omission!

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2608/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13919/ui-diff)

**Review by jeremie-lucca — DISMISSED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2608/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13937/ui-diff)

**Pull request merged**
