### PR TITLE
[feat] dropdown first draft

### LINKED ISSUE #409: dropdown
its a special kind of popover
specify dropdown

### PR DESCRIPTION
**Pull request by lucienbertin**
fixes #409 

frist draft of the dropdown

currently it contains

- directive `[luDropdown]` to put on a button where you want to aatach a dropdown
- component `<lu-dropdown>`, panel that will be opened - equivalent to a `<lu-popover>`
- directive `luDropdownItem` - this is not mandatory it is used by the panel to know when one is clicked and it should close itself

target dev html is
```html
<button class="button" [luDropdown]="dropdown">this button has a dropdown</button>
<lu-dropdown #dropdown>
	<li class="lu-dropdown-options-item" >
		<a routerLink="." fragment="link1" class="lu-dropdown-options-item-action" luDropdownItem>Link 1</a>
	</li>
	<li class="lu-dropdown-options-item">
		<a routerLink="." fragment="link2" class="lu-dropdown-options-item-action" luDropdownItem>Link 2</a>
	</li>
	<li class="lu-dropdown-options-item" >
		<a routerLink="." fragment="link3"  class="lu-dropdown-options-item-action" luDropdownItem>Link 3</a>
	</li>
	<li class="lu-dropdown-options-item" >
		<button class="lu-dropdown-options-item-action" luDropdownItem (click)="debug(4)">Button 4</button>
	</li>
	<li class="lu-dropdown-options-item" >
		<div role="button" tabindex="0" class="lu-dropdown-options-item-action"  (click)="debug(4)" luDropdownItem>Div 5</div> <!-- it doesnt work with divs or tags not focusable -->
	</li>
</lu-dropdown>
```

----

it does not contain
- collapsable stuff for sub links
- some other things tha t i forgot
- navigation in the dropdown via arrow-keys

closes #1002

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1010

**Comment by lucienbertin** [comment]
reviewavble on http://lucca-front.lucca.local/PR-1010/ng#dropdown

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1010

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1010

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1010

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1010

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1010

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1010

**Pull request merged**
