### PR TITLE
[numericBadge] loading

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

-----

-----

Capture d’écran 2024-12-02 à 15 53 05

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3134/storybook

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3134/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3134/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3134/storybook

**Pull request merged**
