### PR TITLE
Revert 2336 rc

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Reverting 16.4 commit because it has been merged with squash to remake the 16.4 release properly, including a hotfix at the same time for prod build of ngClazz directive

-----

-----

### CODE REVIEW

**Review by shajz — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2345/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7816/ui-diff)

**Comment by jeremie-lucca** [comment]
Sorry 🙈

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2345/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7818/ui-diff)

**Pull request merged**
