### PR TITLE
fix(tooltip): too many reflows

### PR DESCRIPTION
**Pull request by GuillaumeNury**
## Description

Each time a width is read after a class has been added or the dom has been updated, the browser recompute all layers (reflow). Before this PR, this occured **twice per tooltip**.
Now, this append twice, whatever number of tooltip is appended at the same time.

Before:
image

After:
image

-----

Optionally, technical or more in-depth description for reviewers.
Keep an empty line under your text, as well as the 5 lines that follow it.

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3225/storybook

**Comment by jeremie-lucca** [comment]
@GuillaumeNury Tooltips on buttons seems to be down (e.g. [this story](https://lucca-front.lucca.tech/PR-3225/storybook/?path=/docs/documentation-overlays-tooltip-basic--docs) or [this one](https://lucca-front.lucca.tech/PR-3225/storybook/?path=/story/documentation-overlays-tooltip-real-time-update--basic)). Could it be related to this PR ?

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3225/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3225/storybook

**Review by Supamiu — APPROVED** [review]

**Pull request merged**
