### PR TITLE
Remove tooltip generated by Safari desktop

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Disables the tooltip automatically generated by Safari when it detects truncated text.

-----

-----

Before:
Capture d’écran 2024-07-16 à 17 33 11

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2958/storybook

**Review by LucasPat — DISMISSED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19720/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2958/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21182/ui-diff)

**Pull request merged**
