### PR TITLE
Border-radius full

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

- [x] Mutualize `50%` and `9999px` values, which in the end do the same thing (depending on the shape of the element to which it applies);
- [x] include this in variables rather than hard numbers.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2501/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11663/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2501/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11664/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2501/storybook

**Review by ymalie-lucca — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11666/ui-diff)

**Pull request merged**
