### PR TITLE
Change default icon color

### LINKED ISSUE #2918: [Empty states] Icon action color
Icon action colors should be : 
- Brand 600 (Currently ~~Product~~ Primary 600) by default
- Success 600 in Success state
- Critical 600 in Critical state

Note, these icons are on CDN, generated by a script and still refer to `primary` color as fallback.
I suggest to keep this primary reference to prevent breaking changes on production but apply a `brand 600` color when necessary on LF side.

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Fix #2918 

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2924/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19372/ui-diff)

**Review by AlexiaAlarza — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2924/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19556/ui-diff)

**Pull request closed without merging**
