### PR TITLE
Adjustements for comment component

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

- [x] Fix avatar alignement in narrow spaces.
- [x] Extracts responsive logic from the index so that it can be modified if necessary.
- [x] Using the mixin container (and a small correction to it).
- [x] Bullet not rendered in screen readers.
- [x] Some variables now based on spacings.
- [x] Delete some `displays: flex`.
- [x] Use of a `time` tag for dates and times.
- [x] The modifier `compact` is managed with a class, eliminating the need to modify HTML and improving accessibility.
- [x] Reset on rich mode elements applied only to direct children.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2811/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17305/ui-diff)

**Review by LucasPat — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2811/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17308/ui-diff)

**Pull request merged**
