### PR TITLE
feat(text-input): add url as valid type

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Title says it all, we most likely overlooked this type when first implementing text input component.

-----

-----

### CODE REVIEW

**Review by martincadoux — DISMISSED** [review]
🙏

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2769/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/16666/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2769/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/16686/ui-diff)

**Pull request merged**
