### PR TITLE
[feat] user select scoped search

### LINKED ISSUE #414: user-slect - handle permission scopes
either with a different `user-paged-searcher` or by enriching the user paged searcher

### PR DESCRIPTION
**Pull request by lucienbertin**
fixes #414 

added `@Input` appInstance and operations to user select input and user-searcher components

- if none are specified, it uses `/api/v3/users/search`
- if some are specified, it switches to /api/v3/users/scopedSearch`

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://454-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://454-pr-lucca-front-LuccaSA.surge.sh

**Comment by jeremie-lucca** [comment]
First time I scroll over the popover, scroll focus is done on page and not on popover content : 

(works well the second time I scroll in)

**Comment by jeremie-lucca** [comment]
And idk if it's on the scope, but multiple user selection looks to be broken : 
image

**Comment by lucienbertin** [comment]
@jeremie-lucca 
- i dont reproduce the bug with _multiple_
- teh scroll issue is also a bug on master, i created issue #445 and i'll try to fix it from master, so its not in the scope of this PR

**Comment by jeremie-lucca** [comment]
:shipit:

**Pull request merged**
