### PR TITLE
feat(scss) Positions and placements utilities

### LINKED ISSUE #1162: [scss] utility to put an element fixed in a corner
somethng like `u-fixedBottomRight` to ease the placements of buttons like in this moqup

image

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
Added atomic classes for positioning.

Fix #1162

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1168

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1168

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1168

**Review by sanlucca — COMMENTED** [review]
Aren't there already some existing ones ?

**Comment by vvalentin-lucca** [comment]
> Aren't there already some existing ones ?

I found nothing on a global level.

**Review by sanlucca — APPROVED** [review]

**Pull request merged**
