### PR TITLE
LF 16.4

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Actions required to update
- We removed font variable coverage as it was heavier than our 4 needed weights. `$fontVariable` must be removed if overrided to `true`.

### 🎉 Features
- [Multi Select] New Angular component #2264
- [Fields] New Angular field components (`textField`, `checkboxField`, `switchField`) based on [new HTML components](https://github.com/LuccaSA/lucca-front/releases/tag/v16.3.0) #2311 
- [Fieldset] New HTML component #2242 
- [Skeleton] New HTML component #2322 
- [Icon] New Angular component #2302
- [Vertical navigation] Icon and sections support #2270 
- [Box] New box arrow feature related to fields `:checked` status #2314 
- [Colors] Add decorative palettes #2280 #2289
- [Colors] Add Lucca's orange palette #2308 
- [Utilities] Add overflow utilities #2275 
- [Utilities] Add a first batch of logical properties utilities #2312 
- [Icons] New icons `heart filled`, `bookmark`, `bookmark filled`, `thumb up filled`, `thumb down filled` #2306 

### 🎨 Visual changes
- [Colors] Update grey (50/100/200) colors (quite darker) #2324 
- [Titles] Apply `text-wrap: balance` to improve words balance between lines of text #2299  
- Use uppercase for date format (iso 8601) #2279 
- [Icons] Fix icons sizes when using size mods, add size mixins and apply them to _Button_ & _Action icons_ #2276   

### 🚑 Fixes
- [Table] Fix sortable head cells & arrows #2305  
- [Colors] Replace default background color (`#F5F5F5` by `var(--palettes-grey-25)`) and fix background colors of a few components (`menu`, `field-input`, `verticalNavigation` & `pageHeader`) #2277 
- [Callout] Fix _clear_ cross color when used in a _callout_ context #2266 
- [Button] Fix padding for `mod-icon` and `mod-S` combination #2262
- [Button] Fix border when combining `disabled`, `mod-outlined` and a palette #2260
- [Icon] Fix company icon misspelling #2321 
- [Numeric Badge] Has `span` element by default instead `div` to be used in `button` #2325 

### 🔨 Technical
- [Pagination] Update stories icons #2295 
- Remove font variable & related utilities #2285 
- [Grid] Edit stories to avoid workaround classes #2284 
- [Modal] Remove old firefox padding hack #2281 
- [Select] Remove `!important` on `gap` and `padding` for `select-input` to reduce specificity #2263
- [Storybook] Remove relicate inputs #2256 
- [Readme] fix paths related documentation #2309 
- [Icons] Improve icons update process #2327 

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2336/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7689/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2336/storybook

**Review by shajz — DISMISSED** [review]

**Review by Supamiu — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7712/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2336/storybook

**Review by Supamiu — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7723/ui-diff)

**Review by vvalentin-lucca — APPROVED** [review]

**Review by AlexiaAlarza — APPROVED** [review]

**Review by shajz — APPROVED** [review]

**Pull request merged**
