### PR TITLE
feat(footer): Angular wrapper for footer

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

This is a simple wrapper for the footer component, simple but more details below

-----

This also includes first implementation of lu-portal as this is the first time we need it. The `lu-portal` component aims at providing an easy way to have inputs that can support `string | TemplateRef` and render accordingly, in order to mix ease of use and complexity when needed.

It's open to discussion as there's multiple ways to implement this, I chose to use a function call in template + OnPush to prevent performance impacts so I could have proper typing, as it's the only way I found to have the compiler understand when `content` is a `TemplateRef` and when it's not (other approaches just lead to compiler being angry because `*ngIf` is on a boolean, meaning that it doesn't infer the correct type for `content` at all).

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2239/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5896/ui-diff)

**Review by GuillaumeNury — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2239/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5928/ui-diff)

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2239/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/6117/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2239/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/6120/ui-diff)

**Review by shajz — APPROVED** [review]

**Comment by Supamiu** [comment]
Closing this because it's a bit old and fotters are being redesigned anyways.

**Pull request closed without merging**
