### PR TITLE
Remove font variable option and remove utilities not present in DS

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Why remove the variable font? 
It's heavier than the 4 files needed to manage the different weights.

(💥 `$fontVariable: true` must be removed if you use it.)

Why delete utilities?
These weights are not present in the DS.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2285/storybook

**Review by MarcFairbrother — DISMISSED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/6574/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2285/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/6576/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
