### PR TITLE
[EmptyState] Tweaks for narrow views

### LINKED ISSUE #2520: [Empty State] Reduce title size on small resolutions
Title should have a H2 style on small resolution.
Clément suggest < 480px

image
https://www.figma.com/file/PKgmQtFDKpwYlSUSpcJcMo/Lucca-templates?type=design&node-id=8924%3A45888&mode=design&t=kd38kg7nIY4wYQNU-1

### PR DESCRIPTION
**Pull request by fbasmaison-lucca**
## Description

* Reduce heading to match `h2` styles.
* Address buttons based on the mockups provided.

Closes #2520.

-----

https://github.com/LuccaSA/lucca-front/assets/144820795/d93e5326-50ec-4a9b-9ee7-311cb79b5aba

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2725/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15949/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2725/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15972/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2725/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15974/ui-diff)

**Pull request merged**
