### PR TITLE
[Components v3] Mobile navigation

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

New CSS components : Mobile navigation

-----

image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2189/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5007/ui-diff)

**Review by RipripKipkip — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2189/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5287/ui-diff)

**Review by RipripKipkip — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2189/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5319/ui-diff)

**Review by RipripKipkip — APPROVED** [review]

**Pull request merged**
