### PR TITLE
[Form v2] Textfield

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

New Textfield component
Note : In order to keep form v2 inputs nomenclature clean (_radioField_, _checkboxField_, _switchField_, _textField_), I had to rename to current `textfield` folder in `textfields`. So the component import is edited, but the classes are unchanged.
The best option I found is to keep `.textfield-xxx` for current textfield and `.textField-xxx` for the V2 component. 

-----

image
image

https://github.com/LuccaSA/lucca-front/assets/25581936/d16e1a9e-a855-4a00-b188-5f79ca54037f

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2208/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5306/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2208/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5307/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2208/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5320/ui-diff)

**Pull request merged**
