### PR TITLE
[Feat] options.selector

### LINKED ISSUE #385: option-operator for sellection
have an operator that adds a checjbox `select all` when using a salect multiple

needs a redefinition of what a `ALuOptionSelector` is and how the picker listens to it

### PR DESCRIPTION
**Pull request by lucienbertin**
⚠️ postponed to next major ⚠️ 

fix #385 

https://792-pr-lucca-front-luccasa.surge.sh/ng/#/option-selector

@sanlucca or @jeremie-lucca i need some stylin' of it, see file _option-selector.scss

also i might need to

- [x] intl !!!
- [x] style
- [ ] check that it didnt broke api-operators / user-operators
- [ ] create api-operator that does all (feeder, searcher, pager, selector)
- [ ] same but with user
- [ ] make the tree-option-selector also

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://792-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://792-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://792-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://792-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://792-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://792-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
PR rebased on #852 after PR #851 reworks the picker structure

**Pull request closed without merging**
