### PR TITLE
Table.layout fixed.and.sticked.overhaul

### PR DESCRIPTION
**Pull request by BertrandPodevin**
## Description

sticky-cols

**Fixes (non breaking) :**

- Fix table sticky colums & header drop shadow on scroll not working. (Drop shadow are currently always visible, they should only be visible on scroll)
- Simplified DOM : `mod-columnSticky-shadowMask` class no longer needed

**Overhaul :**

- New system using css vars instead of class for the inner settings, drasticaly reducing dist size

`tableFixedLegacy` : 37 Ko --> `tableFixed` : 2 Ko
`tableStickedLegacy` : 52 Ko --> `tableSticked` : 8 Ko

-----

### CODE REVIEW

**Comment by jeremie-lucca** [comment]
Check with Guillaume if we can have schematics.

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2126/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11442/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2126/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11491/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11542/ui-diff)

**Pull request closed without merging**
