### PR TITLE
Angular 13 support

### PR DESCRIPTION
**Pull request by shajz**
## Description

🔨 Technical
- `Angular 12` -> `Angular 13` which makes this LF 8. LF 8 requires ng 12 or 13.
- Switched to `npm@7`
- Simplified `tsconfig.json` and `tsconfig.lib.json` (only one file of each)
- Simplified `angular.json` and `ng build` A LOT. Only one project in `angular.json` now builds every ng package, bye bye complicated `gulp` tasks, bye bye `angular.json` madness. Build is much faster too.
  - Removed each project's now unncessary `package.json` and simplified their `ng-package.json` file
  - Removed `root` package, now unnecessary and moved `ng/root/styles` to `ng/styles`
- Bumped `tsconfig.json` target to `es2017` (from `es2015`)
- `noImplicitOverride`, `noPropertyAccessFromIndexSignature`, `noImplicitReturns` requirements in tsconfig
- Removed `npm links` to `scss` and `icons`. They are now linked automatically via the `workspace` property in package.json. Simple!
- Fixed `storybook` build hell. The version is fixed to 6.4.0 and the code doesn't seem to work when bumping the dep... For now this will do

🥊 Hacks

- Used the hack mentionned in this issue when we have generics extending our types : https://github.com/angular/angular/issues/43624#issuecomment-929035344. It's ugly but it works...

🚑 FIX
- Fixed `@angular/cdk` deprecations regarding overlay positions
- Replaced deprecated `PortalInjector` by `Injector.create`
- Fixed `LuDepartmentSelectInputComponent` extending `ILuTreeOptionPickerPanel` instead of `ILuOptionPickerPanel`
- Fix `/` usage in `.scss` files, bye bye annoying warnings

💥 Breaking changes for users

- You need to add `node_modules` directly to your `stylePreprocessorOptions`
- [scss] You must remove the `~` in all imports, for example `@import '~@lucca-front/ng/style/main';` becomes `@import '@lucca-front/ng/style/main';`
- `LuOptionPickerAdvanced` exported as `LuOptionPickerAdvanced` instead of `LuOptionPicker` (see https://angular.io/api/core/Directive#exportAs)

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Review by GuillaumeNury — DISMISSED** [review]

**Review by GuillaumeNury — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Review by GuillaumeNury — APPROVED** [review]

**Comment by shajz** [comment]
Let's merge straight to master as v8.0.0 will only include this change.

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1488

**Review by MarcFairbrother — APPROVED** [review]

**Pull request merged**
