### PR TITLE
Fix table sort + story

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

[Sorting into tables was no longer working](https://github.com/LuccaSA/lucca-front/issues/2303), so I added a story to test and correct it.

-----

-----

Capture d’écran 2023-10-03 à 11 53 51

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2305/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7258/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2305/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7268/ui-diff)

**Pull request merged**
