### PR TITLE
chore(rc): fixes for issues noticed with rc.2 tests

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

This PR fixes:
- Missing scss import in `lu-form-field` resulting in size not being applied properly
- Wrong injector used in `LuDialogService`, resulting in issues in any dialog component that needs injection (hello transloco)
- Wrong injector used for `LuModal` adapter, resulting in the same as above for `LuModal` boxes
- Placeholder label updates not being applied properly in `lu-multi-select`, breaking transloco usages for placeholders

-----
-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2593/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13827/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2593/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13846/ui-diff)

**Pull request merged**
