### PR TITLE
[container] vars move to common

### LINKED ISSUE #3096: [Table / Index Table] Empty state & overflow
When Tables have horizontal scroll, empty state can appears offscreen as it based on `100rem`'s container max width (`--components-container-max-width`).  

We could fix it by overriding this value in `.table .emptyState` & `.indexTable .emptyState` context (maybe with a calculation in `vw` and substracting navside width) 

image

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Container variables are set to global, which simplifies components that used the container.

This PR also includes the PR #3125 and fixes #3096.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3132/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3132/storybook

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3132/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3132/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
