### PR TITLE
feat(popover2): hover+focus trigger mode

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

On Focus, opens popover after the debounce specified by `luPopoverOpenDelay`.

On `Tab` with popover opened, focus on close button then popover's content, then trigger button again.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2895/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18844/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Comment by Supamiu** [comment]
closes #2879

**Comment by jeremie-lucca** [comment]
As we discussed hover+focus interactions : 
- Popover opened by focus (not hover) should be modal to trigger close on backdrop click
- `shit + tab` when focus is on trigger should close the popover

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2895/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19272/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2895/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19312/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2895/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21032/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
