### PR TITLE
[Components v3] New Badge

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Add CSS component New Badge (for navside & tabs) 

-----

image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2185/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4955/ui-diff)

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2185/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5145/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2185/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5290/ui-diff)

**Review by RipripKipkip — APPROVED** [review]

**Pull request merged**
