### PR TITLE
Stories fix

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Minor stories fix

-----

### CODE REVIEW

**Review by almonais — DISMISSED** [review]

**Review by almonais — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2246/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5983/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2246/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5986/ui-diff)

**Pull request merged**
