### PR TITLE
Revert translate for loading position

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2904/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19023/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2904/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19555/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
