### PR TITLE
[uiDiff] Test for all structure comp

### PR DESCRIPTION
**Pull request by JeSuisCharlie1**

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1802/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1802/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1802/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1802/storybook

**Review by shajz — APPROVED** [review]
🙈

**Pull request merged**
