### PR TITLE
feat(scss) palettes overhaul

### LINKED ISSUE #1328: [DS to LF] Palette grey and text
Modify palette grey to use the new common palette grey : https://www.figma.com/file/sO3msermeMuyFvUAcXrbn5/Main-Components-2.0?node-id=3%3A27

**Don't forget to modify the palette text**

Capture d’écran 2021-05-26 à 15 35 25

### LINKED ISSUE #1329: [DS to LF] Palettes warning, error, success
Modify the all common palette warning, error and success : https://docs.google.com/spreadsheets/d/1PpCTWjGDFzsG08LZaN2_213x5PBrTHaCKsT9IfSqw6k/edit#gid=0

Capture d’écran 2021-05-26 à 15 37 57

### LINKED ISSUE #1330: [DS to LF] Palette primary, secondary
Modify the primary and secondary colors to identify them correctly (hover, active...). 
Choose the main colors : https://www.figma.com/file/sO3msermeMuyFvUAcXrbn5/Main-Components-2.0?node-id=3%3A27

Capture d’écran 2021-05-26 à 15 41 29

### PR DESCRIPTION
**Pull request by BertrandPodevin**
fixes #1328 
fixes #1329 
fixes #1330

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1377

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1377

**Review by sanlucca — CHANGES_REQUESTED** [review]
Leave the primary and secondary to its grey state

**Review by sanlucca — CHANGES_REQUESTED** [review]
The primary/secondary needs to stay greyish

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1377

**Review by sanlucca — APPROVED** [review]

**Pull request merged**
