### PR TITLE
feat(ng) style for cdk drag n drop

### LINKED ISSUE #420: drag n drop
Add classes to handle Drag & Drop in our apps

### PR DESCRIPTION
**Pull request by almonais**
image

closes #420

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Review by sanlucca — COMMENTED** [review]
There is a slight border-radius on items not dragged when you start dragging
image

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Review by RipripKipkip — APPROVED** [review]

**Review by lucienbertin — APPROVED** [review]

**Review by sanlucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1128

**Pull request merged**
