### PR TITLE
Fix Story deprecated

### PR DESCRIPTION
**Pull request by g-drouard**
## Description

Replace Story => StoryFn
Remove useless parameter type

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2509/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11729/ui-diff)

**Review by GuillaumeNury — DISMISSED** [review]
Nice!

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2509/storybook

**Review by GuillaumeNury — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
