### PR TITLE
Implicit labels

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
Implicit labels to enlarge click areas and improve accessibility. Bonus: no more need for the for/id couple.

-----

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1060

**Comment by lucienbertin** [comment]
To what extend is it a breaking change ? is the old synthax still supported ?

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1060

**Comment by vvalentin-lucca** [comment]
No impact on current process, only the examples are updated.

**Comment by lucienbertin** [comment]
> It seems this needs to be rebased on RC ?

done

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1060

**Pull request merged**
