### PR TITLE
Fix palettes colors

### PR DESCRIPTION
**Pull request by AlexiaAlarza**
Fix palette colors of warning and error

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1443

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1443

**Review by MarcFairbrother — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1443

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1443

**Pull request merged**
