### PR TITLE
LF 17.2

### PR DESCRIPTION
**Pull request by jeremie-lucca**
### Actions required to update
1. [Simple & Multiple Select] Old dependency to textfield's style was removed in order to provide common style for fields and improve components maintainability on long run.

It means that for Simple & Multiple Select, HTML structures likes: 
```
<label class="textfield">
  <span class="textfield-label">...</span>
  <lu-simple-select class="textfield-input"></lu-simple-select>
</label>
```
must be refactored without `.textfield` references like: 
```
<lu-form-field>
  <lu-simple-select></lu-simple-select>
</lu-form-field>
```
[Add link to full documentation]
... or:
```
<div class="form-field">
  <label class="formLabel">Label</label>
  <lu-simple-select></lu-simple-select>
</div>
```
[Add link to full documentation]

2. In very rare cases where new components `<lu-textfield>`, `<lu-radiofield>`, `<lu-switchfield>` or `<lu-checkboxfield>` are used, a new DOM has to be used to improve components customization on the long run. [More details](https://github.com/LuccaSA/lucca-front/pull/2502).

3. In order to fix icons size inconsistency bewteen Figma, HTML and Angular component, default icon size on HTML component was increased from `20px` to `24px`. It's recommended to have `24px` as default value, but if you want to stay with `20px`, it's still possible to update icon size variable at your project root `:root { --icon-size: 1.5rem; }`, or apply `mod-S` to specifics icons.

### 🎉 Features
- [Simple / Multiple select] Major design refactor 💥  https://github.com/LuccaSA/lucca-front/pull/2467 
- [New fields] Refactor the way fields are used as Angular components to make them more flexible 💥 https://github.com/LuccaSA/lucca-front/pull/2502
- [Empty state] New HTML/CSS and Angular component https://github.com/LuccaSA/lucca-front/pull/2369
- [Radiofield] New HTML/CSS component https://github.com/LuccaSA/lucca-front/pull/2482
- [Button] Action icon as button mod https://github.com/LuccaSA/lucca-front/pull/2438
- [Colors] New shades for decorations palettes https://github.com/LuccaSA/lucca-front/pull/2493
- [Textfield] Add password toggle option https://github.com/LuccaSA/lucca-front/pull/2434
- [Grid] New breakpoint classes to manage auto display https://github.com/LuccaSA/lucca-front/pull/2489
- [Divider] Add option to include text of action content https://github.com/LuccaSA/lucca-front/pull/2429
- [Callout disclosure] Add open control https://github.com/LuccaSA/lucca-front/pull/2458
- [Vertical navigation] Add iconless option https://github.com/LuccaSA/lucca-front/pull/2436
- [User select] Add option to disable format display on main user name https://github.com/LuccaSA/lucca-front/pull/2488
- [Icons] New icon weather lightning https://github.com/LuccaSA/lucca-front/pull/2517
- [Mixins] New rangeQueries mixins https://github.com/LuccaSA/lucca-front/pull/2426
- [Utilities] New white space pre line utility https://github.com/LuccaSA/lucca-front/pull/2483
- [Border radius] Provide a _full_ radius variable https://github.com/LuccaSA/lucca-front/pull/2501

### 🤖 Schematic
- [Icons] Provide a script command to update icon names : `ng g @lucca-front/ng:new-icons` https://github.com/LuccaSA/lucca-front/pull/2468

### 🎨 Visual changes
- [Icon] Increase default size (`S` > `M`) 💥  https://github.com/LuccaSA/lucca-front/pull/2435
- [Modal / Sidepanel] Increase title size https://github.com/LuccaSA/lucca-front/pull/2481
- [Callout popover] Fix icon size & border radius on XS size https://github.com/LuccaSA/lucca-front/pull/2491
- [Callouts] Fix components height https://github.com/LuccaSA/lucca-front/pull/2466
- [Card] Improve focus style on action mod https://github.com/LuccaSA/lucca-front/pull/2470

### 🚑 Fixes
- [Callout popover] Fix gap issue on iconless mod https://github.com/LuccaSA/lucca-front/pull/2480 
- [Select] Fix french translation typo https://github.com/LuccaSA/lucca-front/pull/2473
- [Palettes] Fix default states palettes import https://github.com/LuccaSA/lucca-front/pull/2460
- [Textfield deprecated] Fix background color on clear button https://github.com/LuccaSA/lucca-front/pull/2456
- [Grid deprecated] Fix compilation issues https://github.com/LuccaSA/lucca-front/pull/2449
- [Datepicker] Fix icon rotation https://github.com/LuccaSA/lucca-front/pull/2446
- [File] Improve hover style https://github.com/LuccaSA/lucca-front/pull/2437
- Fix style import on a bunch of wrapped components https://github.com/LuccaSA/lucca-front/pull/2452 https://github.com/LuccaSA/lucca-front/pull/2445
- Fix change detection issues not applied properly on ngClass https://github.com/LuccaSA/lucca-front/pull/2459

### 📖 Documentation
- [Grid] Improve responsive documentation https://github.com/LuccaSA/lucca-front/pull/2479
- [Icons] Add XXS size documentation https://github.com/LuccaSA/lucca-front/pull/2451
- Add update documentation on readme https://github.com/LuccaSA/lucca-front/pull/2450

### 🔨 Technical
- [Skip Links] Use inject syntax https://github.com/LuccaSA/lucca-front/pull/2485
- [Colors] Improve color variables management https://github.com/LuccaSA/lucca-front/pull/2441
- Remove calculation warning https://github.com/LuccaSA/lucca-front/pull/2486
- Bumb Jenkins shared lib https://github.com/LuccaSA/lucca-front/pull/2455
- Fixed dompurify dependency for ESBuild + Vite compatibility https://github.com/LuccaSA/lucca-front/pull/2503

### 🦕 Deprecated
- `.actionIcon` component (replaced by `.button.mod-onlyIcon`)
- `.button.mod-icon` class (replaced by `.button.mod-withIcon` to avoid confusion with `.button.mod-onlyIcon`)

[All information related to deprecated elements](https://prisme.lucca.io/94310e217/p/40c515-elements-deprecies)

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11639/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11682/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11699/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11754/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11794/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11895/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2497/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11906/ui-diff)

**Review by vvalentin-lucca — APPROVED** [review]

**Review by GuillaumeNury — APPROVED** [review]

**Pull request merged**
