### PR TITLE
surge - enable hash navigation

### PR DESCRIPTION
**Pull request by lucienbertin**

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://658-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
its still broken, dont merge

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://658-pr-lucca-front-LuccaSA.surge.sh

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://658-pr-lucca-front-LuccaSA.surge.sh

**Pull request merged**
