### PR TITLE
Feat.textfield.remove.palettes

### LINKED ISSUE #755: [textfields] Remove palettes ?

### PR DESCRIPTION
**Pull request by jeremie-lucca**
fixes #755

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://793-pr-lucca-front-LuccaSA.surge.sh

**Comment by lucienbertin** [comment]
@jeremie-lucca is it associated with an issue ?

**Comment by jeremie-lucca** [comment]
@lucienbertin Yep, soz : https://github.com/LuccaSA/lucca-front/issues/755

**Comment by LuccaIntegration** [comment]
Travis automatic deployment: https://793-pr-lucca-front-LuccaSA.surge.sh

**Pull request merged**
