### PR TITLE
feat(scss) scroll smooth utilities

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
Added soft scrolling for document, and utilities to disable or enable it in other places.

----

Before:
uh06TbiiYt

After:
DbcjcXV88r

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1203

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1203

**Review by BertrandPodevin — APPROVED** [review]

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1203

**Comment by sanlucca** [comment]
Closes #1196

**Pull request merged**
