### PR TITLE
Package icons

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
- [x] Removal of the icon component which was only a shortcut to the package.
- [x] The mixin and the associated classes are moved to package.

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1717

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://recette-auto.lucca.fr/lucca-front-96-6a0afd5b-4591-459e-9cd2-016f20205c87/ui-diff.html)

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1717

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://recette-auto.lucca.fr/lucca-front-97-38ee1506-29c5-477c-9fcd-111d8a1b1582/ui-diff.html)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://recette-auto.lucca.fr/lucca-front-99-089ccb98-02b8-4d5b-a75b-829fe12e8560/ui-diff.html)

**Review by BertrandPodevin — APPROVED** [review]

**Review by GuillaumeNury — APPROVED** [review]

**Pull request merged**
