### PR TITLE
Change backgrounds colors

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

- [x] Using colors from the palette.
- [x] Default light grey color.
- [x] Addition of grey 50.
- [x] Using surface tokens.

-----

-----

Capture d’écran 2024-01-16 à 15 57 36

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2516/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2516/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11896/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11897/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
