### PR TITLE
LF 18.3

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Dialog's scroll in now specifically positioned on content (instead on full component, including header and footer). It might affect custom dialogs that should be carefully reviewed.

#### Containers vars
In order to reuse container's CSS vars on multiple components, some of them must be replaced and applied to `:root`:
```
--components-container-max-width → --commons-container-maxWidth
--components-container-padding → --commons-container-padding
```

### 🎉 Features
- Lucca Front can now be namespaced https://github.com/LuccaSA/lucca-front/pull/3110 (On specific release)
- Improve components responsive management by adding options to switch between `@media` and `@container`, edit default breakpoints and more https://github.com/LuccaSA/lucca-front/pull/2875 (On specific release)
- [Calendar & Date input] New components https://github.com/LuccaSA/lucca-front/pull/3124
- [Select multi] Adds select all option https://github.com/LuccaSA/lucca-front/pull/3030
- [Select core] Adds `enableFormerEmployees` option https://github.com/LuccaSA/lucca-front/pull/3122
- [Comment] Adds Angular component + Chat layout https://github.com/LuccaSA/lucca-front/pull/2866
- [Textarea] Adds `autoResize` option https://github.com/LuccaSA/lucca-front/pull/3062
- [Radio] Adds inline option & cover box arrow option in Radio Angular component https://github.com/LuccaSA/lucca-front/pull/3081
- [Forms] Covers autocomplete option for a bunch of inputs https://github.com/LuccaSA/lucca-front/pull/3069
- [Dialog] Scroll is now restricted to content https://github.com/LuccaSA/lucca-front/pull/3071
- [Dialog] Provides a neutral background content option https://github.com/LuccaSA/lucca-front/pull/3130
- [Dialog] Handle all route config options in `dialogRouteFactory` https://github.com/LuccaSA/lucca-front/pull/3075

### 🎨 Visual changes
- [User tile] Avatar is now aligned on top https://github.com/LuccaSA/lucca-front/pull/3133

### 🚑 Fixes
- [Checkbox] Mixed checkboxes are now rendered correctly https://github.com/LuccaSA/lucca-front/pull/3034
- [Tag] Fix sizes options https://github.com/LuccaSA/lucca-front/pull/3142
- [Tag] Allows decoration palettes https://github.com/LuccaSA/lucca-front/pull/3143

### 🔨 Technical
- [Department] Upgrade to api v4 https://github.com/LuccaSA/lucca-front/pull/2972
- [Secondary nav] Clean up code by compacting width in a single CSS var https://github.com/LuccaSA/lucca-front/pull/3129
- [Container] Improve the way container is used inside layout components https://github.com/LuccaSA/lucca-front/pull/3132
- [Skiplink] Provides a SCSS component https://github.com/LuccaSA/lucca-front/pull/3106

### 💀 Deprecated

[All information related to deprecated elements](https://prisme.lucca.io/94310e217/p/40c515-elements-deprecies)

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3135/storybook

**Review by GuillaumeNury — APPROVED** [review]

**Review by vvalentin-lucca — APPROVED** [review]

**Pull request merged**
