### PR TITLE
fix(scss) display for fieldset in framed forms

### PR DESCRIPTION
**Pull request by MarcFairbrother**
## Description

Adds support for the `fieldset` element in containers with the `.radiosfield` or `.checkboxesfield` classes.

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1497

**Review by AlexiaAlarza — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1497

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1497

**Comment by shajz** [comment]
A rebase, ça embarque des commits de merge d'autres PR

**Review by AlexiaAlarza — APPROVED** [review]

**Pull request merged**
