### PR TITLE
[Textfield] Framed placeholder color

### PR DESCRIPTION
**Pull request by jeremie-lucca**
image

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1796/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://recette-auto.lucca.fr/lucca-front-216-c4331521-151f-405f-b4f3-70d461467e68/ui-diff.html)

**Comment by jeremie-lucca** [comment]
@RipripKipkip Done~

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1796/storybook

**Pull request merged**
