### PR TITLE
fix(core-select): do not submit englobing form when hitting enter

### PR DESCRIPTION
**Pull request by GuillaumeNury**
## Description

Do not submit englobing form when selecting an option using enter key.

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2703/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15598/ui-diff)

**Review by shajz — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2703/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15624/ui-diff)

**Pull request merged**
