### PR TITLE
refactor(core): support readonly in many inputs

### LINKED ISSUE #2249: Support readonly typing
Currently the inputs sent to the various lucca-front components and tools don't accept readonly typing.

image

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

This PR adds readonly support to many inputs accross LF components.

-----

This is not possible for every single input because it'd cause compile errors due to some use cases featuring non-readonly data in some BehaviorSubjects or legacy select code.

closes #2249

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2267/storybook

**Comment by shajz** [comment]
Some tests are failing (see CI)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2267/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7504/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]
readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly readonly

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
