### PR TITLE
fix(dialog): close can be disabled specifically for click on backdrop

### PR DESCRIPTION
**Pull request by guillerot**
## Description

Dialog close should not be handled by default by angular/cdk
Close can be disabled for click on backdrop

-----

Optionally, technical or more in-depth description for reviewers.
Keep an empty line under your text, as well as the 5 lines that follow it.

-----

### CODE REVIEW

**Review by obraud — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2906/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19117/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2906/storybook

**Review by Supamiu — APPROVED** [review]

**Review by obraud — DISMISSED** [review]

**Review by F2X — APPROVED** [review]

**Comment by GuillaumeNury** [comment]
Should we land this on main branch?

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2906/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19302/ui-diff)

**Review by F2X — APPROVED** [review]

**Review by martincadoux — APPROVED** [review]

**Review by obraud — APPROVED** [review]

**Pull request merged**
