### PR TITLE
[i18n-input] Added component handling i18n translations for a single input

### PR DESCRIPTION
**Pull request by obraud**
## Description

* Added I18n panel component & model listing i18n translation
* Added first iteration of parent input component, displaying aforementionned panel on target element click. Usable in a form.
⚠️ This is not the final iteration for this component since it does not match LF needs for now

-----
V1:
The input in itself is a attribute component which prevents using it with other attribute component like `luButton`. It also implements `ControlValueAccessor` which will cause conflicts if used with other  `ControlValueAccessor` component or directives.
image

V2:
The input is a text form control. Panel has been simplified to be submit when clicking outside of it.
chrome_qr746Y5S2t

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2462/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/10754/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2462/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/11265/ui-diff)

**Comment by Supamiu** [comment]
Closing in favor of #2890 to use new popover.

**Pull request closed without merging**
