### PR TITLE
upd(scss) use design system colours in palettes

### PR DESCRIPTION
**Pull request by MarcFairbrother**
## Description

The default colour palettes were set to grey values for browsers without `css var` support, we can now use the design system colours for the default palettes.

-----

### Before

Primary:

image

Secondary:

image

### After

Primary:

image

Secondary:

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1510

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1510

**Review by AlexiaAlarza — APPROVED** [review]

**Comment by jeremie-lucca** [comment]
Let's use this PR to apply our new G600 color: `#667799` instead of `#6C7C9D`

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1510

**Review by AlexiaAlarza — APPROVED** [review]

**Pull request merged**
