### PR TITLE
7.0-Rc

### LINKED ISSUE #1307: ng-dpt - support scoped in lu-dpt-select
there's this api that exists

```
/api/v3/departments/scopedtree?appInstanceId=x&operations=y,z
```

so if the `lu-department-select` could support it, the same way the `lu-user-elect` supports it, that'd be great thx

### LINKED ISSUE #1308: Update Header
Update header to new Styleguides

### LINKED ISSUE #1318: ets-select - better display for small tenants
in teh ets-select the grouping by LU is not necessarily super usefull for most of our tenants cuz its only usefull when you have a lot of ets and LU

if we look at the stats we have (\*)

| condition | % of tenants |
| :--- | ---: |
| just 1 ets | 40% |
| less than 6 ets | 80% |
| just 1 LU | 70% |
| etsCnt == luCnt | 55% |
| 2 LU or more && 6 ets or more | 10 % |

the current group by LU display is really usefull only in the last case, so for 10% of our tenants

so we could, when opening the picker, fetch the number of ets and LU (2 http get that should resolve quickly) and use it to choose if we want to group by LU or even if the LU name carries some relevant information

we already swap between a display grouped by LU and not grouped by LU when searching, we just need to plug 2 new booleans into this
 
> \* remember that these stats are *per tenant* but the component is consummed by *end users*. we can/could weight each tenant by its user base size. my gut feeling is that big fat tenants with lots of users are the 10% tenants with lots of LU and Ets ; so the 10% teant stat might look bad but could translate to 40-60% of users

### LINKED ISSUE #1320: support ng 12

### LINKED ISSUE #1328: [DS to LF] Palette grey and text
Modify palette grey to use the new common palette grey : https://www.figma.com/file/sO3msermeMuyFvUAcXrbn5/Main-Components-2.0?node-id=3%3A27

**Don't forget to modify the palette text**

Capture d’écran 2021-05-26 à 15 35 25

### LINKED ISSUE #1329: [DS to LF] Palettes warning, error, success
Modify the all common palette warning, error and success : https://docs.google.com/spreadsheets/d/1PpCTWjGDFzsG08LZaN2_213x5PBrTHaCKsT9IfSqw6k/edit#gid=0

Capture d’écran 2021-05-26 à 15 37 57

### LINKED ISSUE #1330: [DS to LF] Palette primary, secondary
Modify the primary and secondary colors to identify them correctly (hover, active...). 
Choose the main colors : https://www.figma.com/file/sO3msermeMuyFvUAcXrbn5/Main-Components-2.0?node-id=3%3A27

Capture d’écran 2021-05-26 à 15 41 29

### LINKED ISSUE #1331: [DS to LF] Border : change commons divider color
Modify the commons.divider.color to '200' instead of "D6D6D6'
http://prisme.lucca.io/components/integration/theming => search card border color

Capture d’écran 2021-05-26 à 15 44 37

### LINKED ISSUE #1348: [DS to LF] Messages : Callout
- [ ] Put the title in block to make the content go underneath
- [ ] Pay attention to the alignment when there is an icon
- [ ] Change the default background + palette to 100
- [ ] Add borders (200)
- [ ] Be careful with border-radius on icons

Capture d’écran 2021-05-26 à 17 32 55

### LINKED ISSUE #1350: [DS to LF] Messages : Tooltip
Change the default background to 900

Capture d’écran 2021-05-26 à 17 34 36

### LINKED ISSUE #1352: [DS to LF] Tags : Labels
- [ ] Review background (200) and text in 800
- [ ] Add grey palette
- [ ] Add icon
- [ ] Add sizes on mod-number

Capture d’écran 2021-05-26 à 17 38 11

### LINKED ISSUE #1353: [DS to LF] Tags : Tags
Add mod-outlined version
Modify background color to primary 200 instead of 50

Capture d’écran 2021-05-26 à 17 39 00

### LINKED ISSUE #1357: [DS to LF] Navigation : Breadcrumb
Text grey 600

Capture d’écran 2021-05-26 à 17 45 57

### LINKED ISSUE #1393: Lupopover - focus and hover
Allow focus + hover on LuPopover component

### PR DESCRIPTION
**Pull request by lucienbertin**
# Breaking changes

## scss breakpoints refactor

see PR #1151 for all details

all breakpoints have been changed and updated to accomodate changing in the resolutions used by people on the interwebz

if you didn't override the breakpoints in the theme you shoiuld be fine, if you didn't use them for your custom style you should be finer. if not, migration is all about renaming stuff so its not too difficult, migration should take about 2 hours

in details you have
- `container` is not centered by default, use `container mod-center`
- `container` size is not changeable through `mod-lg` or `mod-sm`
- all your `grid-lg4` must be renammed accordig to the new breakpoints nomenclature
- if you were overriding the breakpoints, maybe you shouldn't have

# Features

## ng12 official support

this version officially works with ng12, ng 10 is dropped from angular version officially supported

## Redesign

a whole bunch of scss component have been added or redesigned to be closer to the designers moqups - [complete list](https://github.com/LuccaSA/lucca-front/pulls?q=is%3Apr+milestone%3A7.0+label%3A%22DS+to+LF%22+)

# Complete list

- PR #1151 
- PR #1314 
- PR #1323 
- PR #1377 
- PR #1378 
- PR #1379 
- PR #1380 
- PR #1381
- PR #1385
- PR #1387 
- PR #1390 
- PR #1382 
- PR #1392 
- PR #1391 
- PR #1394 
- PR #1399 
- PR #1401 

# Fixes issues

- fixes #1328
- fixes #1329
- fixes #1330
- fixes #1331
- fixes #1357
- fixes #1350
- fixes #1348 
- fixes #1353 
- fixes #1352 
- fixes #1320
- fixes #1308
- fixes #1307
- fixes #1393
- fixes #1318 

# release process

- [x] mega merge
- [x] functionnal 7.0-rc publish
- [ ] third party integration
  - [x] prisme https://github.com/LuccaSA/ux-prisme/pull/447
  - [x] talent https://github.com/LuccaSA/Poplee.Talent/pull/2789
  - [ ] cleemy
- [ ] merge
- [ ] official release

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Review by shajz — APPROVED** [review]
🚀

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1398

**Pull request merged**
