### PR TITLE
refactor(icons): new LuccaIcon type

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

This PR adds the index.d.ts file to @lucca-front/icons so we can use it in ng package to type our `icon` inputs to `LuccaIcon`, which enables compilation time check and autocomplete inside your IDE to grab the icon
This file is generated from the selection.json file that icomoon gives us, then exported to be used in the ng package or in other consumers.

I also took this opportunity to refactor icons-related stories with the new CSF3 story format.

-----

BREAKING CHANGE
This removes the icons-list.js file, which, according to a github search, isn't used anywhere, but better safe than sorry so a check might be needed.
-----

### CODE REVIEW

**Review by GuillaumeNury — APPROVED** [review]

**Review by shajz — DISMISSED** [review]

**Comment by shajz** [comment]
There's a CI build failing with storybook

**Review by shajz — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2216/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5663/ui-diff)

**Comment by Supamiu** [comment]
I converted to draft because the impacts are wider than we originally thought, but it'll be done for sure ! Just not ready to merge yet 😄

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2216/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5866/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5867/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2216/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5894/ui-diff)

**Review by shajz — DISMISSED** [review]

**Review by F2X — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2216/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/6588/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Review by shajz — APPROVED** [review]

**Review by vvalentin-lucca — APPROVED** [review]

**Pull request merged**
