### PR TITLE
Fix word-break

### LINKED ISSUE #1489: User tile use word-break: break-all on name
The user tile component set a `word-break: break-all;` on `user.info`. This properties should never be used because it's 1) super ugly and 2) a cheap way to manage overflow

image

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Better hyphenation management :
- line breaks are made naturally if necessary where words are separated;
- and are forced arbitrarily if words are too long.

Fix #1489 

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2926/storybook

**Review by BertrandPodevin — DISMISSED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19420/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2926/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19554/ui-diff)

**Pull request closed without merging**
