### PR TITLE
LF 10.1

### PR DESCRIPTION
**Pull request by shajz**
## :tada: Features
- [Tooltip] Option to display a tooltip if label has an ellipsis https://github.com/LuccaSA/lucca-front/pull/1768
## :art: Visual changes
- [Select] Fix mod-small height https://github.com/LuccaSA/lucca-front/pull/1821
- [Secondary nav] Fix arrows size https://github.com/LuccaSA/lucca-front/pull/1803
- [Textfield] Fix placeholder / icons colors https://github.com/LuccaSA/lucca-front/pull/1796
- [Radio buttons] Fix hover / selected state colors https://github.com/LuccaSA/lucca-front/pull/1792
- [Pagination] Fix prev/next buttons size https://github.com/LuccaSA/lucca-front/pull/1789
- [Files upload] Harmonize UI with Figma https://github.com/LuccaSA/lucca-front/pull/1809
## :heart: Quick win
- [Textfield] Improve responsive by adding a 100% max width https://github.com/LuccaSA/lucca-front/pull/1820
## :ambulance: Fixes
- [Animations] Fix variables https://github.com/LuccaSA/lucca-front/pull/1826
- [Popup] Fix double overlay animation https://github.com/LuccaSA/lucca-front/pull/1805
- [Textfield] Fix sizes variables name https://github.com/LuccaSA/lucca-front/pull/1794
- [Table] Fix handlers position https://github.com/LuccaSA/lucca-front/pull/1793
- [Select multiple] Fix checkbox's icon clipping when opening dropdown https://github.com/LuccaSA/lucca-front/pull/1791
## :hammer: Technical
- Adding specs https://github.com/LuccaSA/lucca-front/pull/1827
- Increase CSS variables coverage https://github.com/LuccaSA/lucca-front/pull/1750

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1833/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1833/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1833/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1833/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1833/storybook

**Review by GuillaumeNury — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
