### PR TITLE
feat(schematics): new CssMapper class for easy CSS schematics along with 3 schematics

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

This PR adds three new schematics:

- `action-icon` which migrates basic uses of `actionIcon` in HTML afiles and puts a comment on top of the `actionIcon` uses in SCSS.
- `palettes` which migrates old palette names to new ones everywhere (TS/HTML/SCSS).
- `tokens-spacing` which migrates CSS vars and classes for the new tokens system regarding spacing everywhere.

-----

In order to make it easier to create schematics for basic SCSS replacements in the future, I created the `CssMapper` class which does all that with just a config as parameter, it's also handling internal requires so we don't have to do it ourselves.

This means that schematics such as `palettes` and `tokens-spacing` are made using a single file containing the usual setup calls and the CssMapper config like so:

```ts
		await new CssMapper(
			tree,
			{
				classes: {
					'palette-grey': 'palette-neutral',
					'palette-primary': 'palette-product',
					'palette-secondary': 'palette-product',
					'palette-lucca': 'palette-brand',
				},
				variables: {
					'--palettes-grey-{val}': `--palettes-neutral-{val}`,
					'--palettes-primary-{val}': `--palettes-product-{val}`,
					'--palettes-secondary-{val}': `--palettes-product-{val}`,
					'--palettes-lucca-{val}': `--palettes-brand-{val}`,
					'--colors-grey-{val}': `--colors-neutral-{val}`,
				},
				mixins: {},
			},
			{
				val: {
					25: '25',
					50: '50',
					100: '100',
					200: '200',
					300: '300',
					400: '400',
					500: '500',
					600: '600',
					700: '700',
					800: '800',
					900: '900',
				},
			},
		).run();
```

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2668/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14927/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2668/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14981/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2668/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15234/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2668/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15236/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2668/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15303/ui-diff)

**Review by GuillaumeNury — DISMISSED** [review]

**Review by jeremie-lucca — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2668/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15375/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
