### PR TITLE
Fix NgClazz directive. 

### PR DESCRIPTION
**Pull request by guillerot**
## Description

NgClazz directive is replaced by LuClass service

-----

see breaking change in "patch" commit of angular/common
https://github.com/angular/angular/pull/53831

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2521/storybook

**Review by GuillaumeNury — APPROVED** [review]
Thx

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12151/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2521/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12152/ui-diff)

**Review by Supamiu — APPROVED** [review]

**Pull request merged**
