### PR TITLE
[phoneNumber + text input] Add autocomplete option

### LINKED ISSUE #3117: [Input] Missing autocomplete attribute
We need the ability to add and populate the HTML `autocomplete` attribute on inputs. 
Additionally, this will prevent Google Chrome from autofilling wrong data

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Added support for the autocomplete attribute. 

Fixes #3117 

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3069/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/22588/ui-diff)

**Review by Supamiu — APPROVED** [review]

**Comment by Supamiu** [comment]
We might want international tel in main input instead to not have to click on the country in prefix input since entering international number will autoselect the right country and format national on blur but this implementation looks fine anyways.

**Comment by vvalentin-lucca** [comment]
@Supamiu I think the problem resides in autocompletion, which is performed on text input rather than on custom select.

**Comment by vvalentin-lucca** [comment]
@jeremie-lucca It's corrected.

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3069/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3069/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3069/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/23601/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3069/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/23608/ui-diff)

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3069/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
