### PR TITLE
feat(scss-a11y) menu : placeholder + aria-current

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
Added a placholder (optional) to avoid jumps when bolding the current page.

Before: 

After: 

Added support for `aria-current="page"`.

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1291

**Review by RipripKipkip — APPROVED** [review]

**Review by BertrandPodevin — COMMENTED** [review]
Nice trick but maybe a little bit complex ? I wonder if we could just instead use a simple text-shadow to fake bold ?
https://codepen.io/bertrandpodevin/pen/abpPqoN

**Comment by vvalentin-lucca** [comment]
Note that the tip remains optional. I'm afraid that visually the fake bold is not very qualitative.

I also did a test on my side to see better: https://codepen.io/vincent-valentin/pen/wvgRybw?editors=1100

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1291

**Pull request merged**
