### PR TITLE
refactor(empty-states): make title and description optional

### LINKED ISSUE #2744: [Empty States] Make description and title optional
## Problem

In some empty states, we may want just a `description` or just a `title`, but at the moment, both of them are required, which means we end up with one of them still present inside the DOM but empty, with all the style applied to it (use case described by @fbasmaison-lucca)

## Possible solutions

The ideal solution would be to have "at least one of them required" but that's not possible with the current tooling that Angular exposes regarding Inputs. Our solution would be to make both of them optional and rely on devs to see that if they don't provide any, well the component is empty and makes no sense.

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Everything is explained in #2744 
-----

closes #2744 and #2622 

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2774/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/16717/ui-diff)

**Review by shajz — APPROVED** [review]
LGTM, but did you check @fbasmaison-lucca's comment here : https://github.com/LuccaSA/lucca-front/issues/2744#issuecomment-2092564053

**Comment by Supamiu** [comment]
Will be checked by UI devs once they're back 🙂 I won't merge without making sure they're fine with what I did here.

**Comment by Supamiu** [comment]
Ping @vvalentin-lucca for a review :)

**Comment by vvalentin-lucca** [comment]
I'll have a closer look tomorrow, but if the title becomes optional, the section tag should move accordingly.

**Comment by jeremie-lucca** [comment]
Fixed. I don't get why but we omitted to add a class on description 🤷
Not breaking but it will be necessary for product teams to add this class to have a good spacing management.

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2774/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17114/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2774/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17117/ui-diff)

**Review by fbasmaison-lucca — DISMISSED** [review]

**Review by vvalentin-lucca — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2774/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17554/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
