### PR TITLE
LF18.1

### PR DESCRIPTION
**Pull request by jeremie-lucca**
#### Removed elements
A bunch of deprecated components & classes has been removed ([see the list](https://prisme.lucca.io/94310e217/p/40c515-cycle-de-vie-des-composants/t/ed1ef06e61)) and need to be replaced if still used.
If you face update troubles due to this deletion, please join us on dedicated slack channel (#lucca-front-public), we keep deleted CSS on hand.

#### Table fixed & sticked import
We provided an updated version of table fixed & sticked that fix shadow bugs and save dist weight.
If you'd rather to update it later, these imports:
```
@forward '@lucca-front/scss/src/components/tableFixed';
@forward '@lucca-front/scss/src/components/tableSticked';
```
... must be replaced by:
```
@forward '@lucca-front/scss/src/components/tableFixedDeprecated';
@forward '@lucca-front/scss/src/components/tableStickedDeprecated';
```

🚧  Add new fixed / sticked table documentation

### 🎉 Features
- [Time & Duration picker] New Angular components https://github.com/LuccaSA/lucca-front/pull/2669
- [Popover] New component to improve accessibility https://github.com/LuccaSA/lucca-front/pull/2852
- [Tooltip & Ellipsis] Improve Tooltip Angular component & new Ellipsis Angular component https://github.com/LuccaSA/lucca-front/pull/2750
- [Select multiple] New counter sub-component (*x elements selected*) https://github.com/LuccaSA/lucca-front/pull/2800
- [Tag] Available as Angular component https://github.com/LuccaSA/lucca-front/pull/2850
- [Comment] New HTML component https://github.com/LuccaSA/lucca-front/pull/2796
- [Scroll box] New HTML component https://github.com/LuccaSA/lucca-front/pull/2565
- [Footer] Supports container & breakpoints options https://github.com/LuccaSA/lucca-front/pull/2843
- [Empty state] Title & description are now optional https://github.com/LuccaSA/lucca-front/pull/2774
- [Empty state] Allow semantic title level override https://github.com/LuccaSA/lucca-front/pull/2814
- [Table] New row & column stick implementation https://github.com/LuccaSA/lucca-front/pull/2743
- [Dialog] Handled `canClose` option in `LuDialogService` https://github.com/LuccaSA/lucca-front/pull/2733
- [Button] Add `delete` option to cover invalid hover style (trash icon) https://github.com/LuccaSA/lucca-front/pull/2773
- [Users] Allow string union type for `luUserInput` format https://github.com/LuccaSA/lucca-front/pull/2789
- [Users] Covers multiple users param on `LuUserDisplayPipe` https://github.com/LuccaSA/lucca-front/pull/2088
- [Textarea] Covers `rows` attribute https://github.com/LuccaSA/lucca-front/pull/2788
- [Textfield] Covers right aligned value style https://github.com/LuccaSA/lucca-front/pull/2810
- [Skeletons] Provide a bunch a loading components https://github.com/LuccaSA/lucca-front/pull/2762
- [Callout] Add actions container with default button sizes https://github.com/LuccaSA/lucca-front/pull/2845 
- [Toast] PortalContent as message (to cover links) https://github.com/LuccaSA/lucca-front/pull/2853
- [Avatar] Provide new component sizes https://github.com/LuccaSA/lucca-front/pull/2848
- Add humanize pipe https://github.com/LuccaSA/lucca-front/pull/2753

### 🎨 Visual changes
- [Toast] New UI https://github.com/LuccaSA/lucca-front/pull/2841
- [User popover] Minor UI improvments https://github.com/LuccaSA/lucca-front/pull/2812
- [User popover] Reduce date format https://github.com/LuccaSA/lucca-front/pull/2825
- [Table] Reduce overflow shadow intensity https://github.com/LuccaSA/lucca-front/pull/2824
- [Textfield] Remove prefix & suffix visual separator https://github.com/LuccaSA/lucca-front/pull/2810
- [Error page] Fix error page UI (color, font style, etc.) https://github.com/LuccaSA/lucca-front/pull/2827
- [Breadcrumb] Increase neutral color from 600 to 700 and replace back arrow icon https://github.com/LuccaSA/lucca-front/pull/2828
- [Select multiple] Align checkbox on top https://github.com/LuccaSA/lucca-front/pull/2854

### 🚑 Fixes
- [Select multiple] Fix "+N" chip size on S size https://github.com/LuccaSA/lucca-front/pull/2855

### 📖 Documentation
- [Forms] Add full form structure examples https://github.com/LuccaSA/lucca-front/pull/2563

### 🔨 Technical
- [Button] `type="button"` is now apply by default on `luButton` when type is not defined https://github.com/LuccaSA/lucca-front/pull/2775
- [Menu] Component refactor https://github.com/LuccaSA/lucca-front/pull/2565
- [Loader] Component refactor https://github.com/LuccaSA/lucca-front/pull/2626
- [Utilities] Remove unwanted automatic classes https://github.com/LuccaSA/lucca-front/pull/2792
- [Font] Add option to switch font family https://github.com/LuccaSA/lucca-front/pull/2801
- New `rosetta` mixin to map new / old CSS vars https://github.com/LuccaSA/lucca-front/pull/2840 
- Add missing german translations https://github.com/LuccaSA/lucca-front/pull/2849

### 💀 Deprecated

[All information related to deprecated elements](https://prisme.lucca.io/94310e217/p/40c515-elements-deprecies)

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/17910/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18013/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18042/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18119/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18120/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18121/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18197/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18206/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18245/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18356/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18360/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18375/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18381/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18434/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2829/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18439/ui-diff)

**Review by vvalentin-lucca — APPROVED** [review]

**Review by GuillaumeNury — APPROVED** [review]

**Pull request merged**
