### PR TITLE
LF 17.4

### PR DESCRIPTION
**Pull request by jeremie-lucca**
### ✅ Actions required to update
Utilities are now loaded by defaut in commons (instead of components), so... 
- Utilities import must be removed (`@forward '@lucca-front/scss/src/components/util';`)
- Keyframes import must be replaced by (`@use '@lucca-front/scss/src/commons/utils/keyframe';`)

### 🤖 Schematics
- `ng g @lucca-front/ng:palettes` Replace grey, primary, secondary & lucca palette by neutral, product & brand.
- `ng g @lucca-front/ng:tokens-spacings` Replace old spacings by new ones.

[See all schematics](https://prisme.lucca.io/94310e217/p/40c515-cycle-de-vie-des-composants/b/15c256)

### 🎉 Features
- [Index Table] New HTML component #2590
- [Tokens] New spacings including intermediate values & more flexibility #2555
- [User Popover] New Angular component #2649 
- [Filter bar] New HTML component #2612 
- [Radio] New Angular component #2674 
- [Textarea] New Angular component #2601
- [Number] New Angular component #2664  
- [Counter] Covers counter as HTML & Angular option for Textfield & Textarea #2500 
- [Form field] Label nows accept `ng-template` #2661 
- [Checkbox] Add _mixed_ option on Angular component #2679 
- [Tags] Cover tags with icons #2581 
- [Grid] New responsive options with container queries #2648
- [Skeleton] Align center & right #2691

### 🎨 Visual changes
- [Chips] Expand clear's button clickable zone #2579 

### 🚑 Fixes
- [Table] Fix background overflow on clickable rows in card #2615 
- [Schematics] Fix nx errors while launching schematics #2690 

### 📄 Documentation
- Provide SCSS component template #2631 

### 🔨 Technical
- [Utilities] 💥 Load utilities by default by moving it from components to commons #2576 
- [Colors] Replace rgba variables by a transparentize fonction based on standard variables #2587 
- [Icons] Reduce component weight thanks to CSS vars & reduce specificity #2595 
- [Callout] Code refacto #2605 
- [Container] Code refacto #2602

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2702/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15591/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2702/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15603/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2702/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2702/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15637/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2702/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15669/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2702/storybook

**Review by GuillaumeNury — APPROVED** [review]

**Pull request merged**
