### PR TITLE
[Secondary nav] Compact alert palette

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Fix compact alert palette

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2681/storybook

**Review by martincadoux — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15186/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2681/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15193/ui-diff)

**Pull request merged**
