### PR TITLE
feat(scss) table header .mod-twoLines

### PR DESCRIPTION
**Pull request by BertrandPodevin**
Added `mod-twoLines` for table header, compatible with other header mods : mod-sortable, mod-alignRight ...

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1121

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1121

**Review by vvalentin-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1121

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1121

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1121

**Pull request merged**
