### PR TITLE
Tooltip

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
- [x] Component NG: tooltip.
- [x] Fix line-height on menu.
- [x] Add control for progress.

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1677

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://recette-auto.lucca.fr/lucca-front-20-3197bb00-3553-4364-ad2c-04ecb9f7ad06/ui-diff.html)

**Comment by jeremie-lucca** [comment]
Something looks wrong on the story 🤔 

(While hovering the first button)

image

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1677

**Review by jeremie-lucca — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://recette-auto.lucca.fr/lucca-front-34-6a419ae3-14ef-47c8-bd4a-9ca813c8a1d1/ui-diff.html)

**Review by shajz — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://recette-auto.lucca.fr/lucca-front-35-10ae9391-3ea8-4b96-b88a-a5e425e2a42f/ui-diff.html)

**Pull request merged**
