### PR TITLE
Component callout refacto

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

- [x] CSS vars

-----

-----

Capture d’écran 2024-02-28 à 15 27 20

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2605/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13912/ui-diff)

**Review by fbasmaison-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2605/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2605/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14989/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14991/ui-diff)

**Review by fbasmaison-lucca — APPROVED** [review]

**Pull request merged**
