### PR TITLE
feat(schematics): add empty-state-heading migration

### PR DESCRIPTION
**Pull request by GuillaumeNury**
## Description

Automatically replace all `title` inputs of empty-states to `heading` input.

-----

Migration has been tested on PEO ([commit](https://github.com/LuccaSA/Poplee.Talent/commit/a873b56bd486bb6756b8b54df03bae1ab9c77a55))

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2955/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/19692/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2955/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2955/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21028/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2955/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21066/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
