### PR TITLE
[Status Badge] Add L size + update colors

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Add L size + update colors

-----

image

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2165/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4487/ui-diff)

**Review by AlexiaAlarza — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2165/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4498/ui-diff)

**Review by almonais — APPROVED** [review]

**Pull request merged**
