### PR TITLE
chore(deps): Storybook 8

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Upgrade storybook to version 8 to hopefully fix ZeroHeight integration issues and get access to its many new features and improvements !

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2714/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15800/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2714/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/15804/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Review by shajz — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
