### PR TITLE
feat(numeric-badge): Angular wrapper

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Implementation of a simple numeric badge wrapper. Which is used as follows:

image

-----

This PR adds some TODOs because it requires some things added in #2166 that should be pushed in a core folder, not to mention story elements like palette that are reused over and over and could definitely use some common code (like the palette input for instance).

This PR requires #2161 to be merged as it depends on it.

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2171/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/4684/ui-diff)

**Comment by shajz** [comment]
CI is failing, I think some exports are KO

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2171/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5633/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2171/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5636/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
