### PR TITLE
[Form v2] Radio

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description
⚠ Merge new-checkbox first, than target RC

New Radio component

-----

image

https://github.com/LuccaSA/lucca-front/assets/25581936/255f8ab8-5e2e-4357-a80f-67582054109d

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2205/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5274/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5275/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2205/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2205/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/5283/ui-diff)

**Review by RipripKipkip — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-2205/storybook

**Pull request merged**
