### PR TITLE
Add animation for submenus

### LINKED ISSUE #2603: [Secondary nav] Add children animation
We should add animation on children item to improve UI:

https://github.com/LuccaSA/lucca-front/assets/25581936/1e0d4354-2748-4d87-b8e7-1e71c3ffba7b

Design suggests to have a vertical / scaling animation here. Let's test if we can figure out how to have good transitions.

https://lucca.slack.com/archives/C04U8CFJKU2/p1709118662648059?thread_ts=1709110125.612239&cid=C04U8CFJKU2

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Reinstates an animation for the appearance of sub-menus that had disappeared by mistake a long time ago.

Fixes #2603 

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2613/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13951/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2613/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13952/ui-diff)

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13958/ui-diff)

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
