### PR TITLE
[Icons] Money Check & Weather Stars

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Add money check & weather stars icons

-----

image

-----

### CODE REVIEW

**Review by vvalentin-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2665/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14840/ui-diff)

**Review by ymalie-lucca — APPROVED** [review]

**Review by vvalentin-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2665/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14896/ui-diff)

**Pull request merged**
