### PR TITLE
[divider] angular wrapper + mod-vertical

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

An Angular wrapper for the divider component.

-----

The separator role should only be added if the divider content is empty, but I haven't managed to do this technically, so we should specify it in the guideline.

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3209/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3209/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3209/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3209/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3209/storybook

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-3209/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
