### PR TITLE
feat(ng) modal-sp a11y

### LINKED ISSUE #1137: modals/sidepanel - better accessibility -  undismissable alert dialogs
for accessibility, there are two kind of dialog : `dialog` and `alertDialog`. the first one is optional and should be dismissable ; while the second one is mandatory and the end user must make a choice

LF should provide tools to use these concepts, for that

- add the correct aria role or attr to the modal/sp panel
- have the correct aria stuff for the buttons that dismiss this modal/sp
- provide a suite of tools to open alertDialogs, which is not currently available un LF

### LINKED ISSUE #1160: [ng] enrich modal submit button in the footer
image (17)

### PR DESCRIPTION
**Pull request by lucienbertin**
better accessibility for modals and sidepanels

- [x] role="dialog" on the popin
- [x] aria-modal="true" on the popin
- [x] focus trap inside the popin
- [x] focus moved to popin
- [x] popin is insde the body
- [x] `esc` and `click-outside` close the popin
- [x] popin isnt in dom when closed
- [x] focus comes back to button opening the dialog after close
- [x] popin in a poppin
- [x] fookin' #1160  - see #1207

wont do in this release

- offer `luModal.confirm(...)`  or some other method to open alertDialogs that cant be dismissed via clickoutside or esc
- some kind of before-dismiss implementation to display a confirmation message that you are about to close a sp/modal with unsaved changes
- some kind of before-submit implementation to handle this #1098 
- impact what is outside the popin - clas `has-dialog` on the dom, aria-hidden = true on the rest of the body ...

closes #1137 
fixes #1160

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1206

**Comment by vvalentin-lucca** [comment]
Great! it's already more accessible this way, thank you.

In the future it will remain: 

- the optional management of the `alertdialog`;
- the `aria-hidden` to put on the rest of the content;
- the addition of a class on the html to avoid multiple scrollbars;
- move the focus to the opening button when closing.

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1206

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1206

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1206

**Pull request merged**
