### PR TITLE
feat: Better sorting and display for grouped select

### PR DESCRIPTION
**Pull request by GuillaumeNury**
## Description

Grouped options, with empty clue:

image

Grouped options, wit clue:

image

-----

Optionally, technical or more in-depth description for reviewers.
Keep an empty line under your text, as well as the 5 lines that follow it.

-----

### CODE REVIEW

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14663/ui-diff)

**Review by Supamiu — DISMISSED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by jeremie-lucca** [comment]
When data are loading, we switch to view were group is associated to value before data are actually loaded, which lead to a weird intermediate state. 
Do we have a we to improve that?

https://github.com/LuccaSA/lucca-front/assets/25581936/51267cd7-041b-4849-838b-4e8ec474361a

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2659/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2659/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/14861/ui-diff)

**Review by Supamiu — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Pull request merged**
