### PR TITLE
feat (scss) : add mod-layoutFixed, sticky columns, sticky columns automatic drop shadow

### PR DESCRIPTION
**Pull request by BertrandPodevin**
Add `.mod-layoutFixed` table, used to precisely size table column from 2 to 20 rem (themable);
Usable globaly or at breakpoint

Add sticky (right, left, or both) column system for table, using `.mod-layoutFixed`

Add `.mod-columnSticky-shadow` for automatic drop shadow on sticky columns when there is an horizontal overflow. Shadow width and color are themables

image

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1382

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1382

**Review by RipripKipkip — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1382

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1382

**Pull request merged**
