### PR TITLE
Numeric badge with a span

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

The numercic badge is more easily embedded in an inline element if it is itself inline rather than block.

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2325/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7535/ui-diff)

**Review by shajz — DISMISSED** [review]

**Review by Supamiu — APPROVED** [review]

**Review by jeremie-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2325/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/7648/ui-diff)

**Review by shajz — APPROVED** [review]

**Pull request merged**
