### PR TITLE
fix(tooltip): remove tooltip on trigger destroy

### PR DESCRIPTION
**Pull request by Supamiu**
## Description

Tooltip used to stay even on trigger deletion, this PR adds a `closeTooltip` call on trigger destroy

-----

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2891/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18770/ui-diff)

**Review by F2X — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2891/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/18803/ui-diff)

**Review by F2X — APPROVED** [review]

**Pull request merged**
