### PR TITLE
Fix invalid label color

### PR DESCRIPTION
**Pull request by audreylemercier**
## Description

Fix of the label color when the input is invalid.
Color : changed from primary to error.

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1924/storybook

**Comment by GuillaumeNury** [comment]
@audreylemercier your branch was created from `master`, do your want to:
* merge your fix on `master`: you can edit this PR to target `master` branch
* merge your fix on `rc`: you can interactive rebase your branch on `rc` and pick only your commit

**Comment by jeremie-lucca** [comment]
@GuillaumeNury We can consider it as a fix so I'm fine with a merge on master (even if it will be released on 10.4 considering our schedule)

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1924/storybook

**Comment by GuillaumeNury** [comment]
@jeremie-lucca I'm ok with that! The target branch was wrong.🙂

**Review by jeremie-lucca — APPROVED** [review]

**Comment by jeremie-lucca** [comment]
@GuillaumeNury Yep, I noticed so I edited it to target master. It's probably the simplest way :)

**Pull request merged**
