### PR TITLE
textfield placeholder with palettes

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
### Fixed issues
- [issue #680](https://github.com/LuccaSA/lucca-front/issues/680) - Textfield palettes does not affect its placeholder nor its hover

Annotation 2020-05-22 114954
Annotation 2020-05-22 115035
Annotation 2020-05-22 115052
Annotation 2020-05-22 115117

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1009

**Comment by lucienbertin** [comment]
@vvalentin-lucca is it a fix or a feature ? if its a fix the the target branch is maste, if its a feature for next release, then the target branch should be rc

**Comment by vvalentin-lucca** [comment]
> @vvalentin-lucca is it a fix or a feature ? if its a fix the the target branch is maste, if its a feature for next release, then the target branch should be rc

Fix! :)

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1009

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1009

**Pull request merged**
