### PR TITLE
Atomic styles for hx

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
- Atomic styles for .u-h1… .u-h6 ;
- rework on sections ;
- linter ok.

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1268

**Review by lucienbertin — APPROVED** [review]
seems ok to me

**Comment by LuccaIntegration** [comment]
jenkins auto deploy http://lucca-front.lucca.local/PR-1268

**Comment by vvalentin-lucca** [comment]
https://github.com/LuccaSA/lucca-front/pull/1269

**Pull request closed without merging**
