### PR TITLE
Navside: replace product by brand for numeric badges

### LINKED ISSUE #2604: [Secondary nav] Brand color on badges
- Numeric badge should use _brand_ palette instead of _product_
- Deprecated variables (`--components-navSide-fullwidth-palette-alert`) should use _brand_ palette instead of _product_
- Sitemap (external project) should be updated to replace alerts references by `numericBadge` and `newBadge`

### PR DESCRIPTION
**Pull request by vvalentin-lucca**
## Description

Fixes #2604 

-----

-----

Before: 
Capture d’écran 2024-02-29 à 17 33 24

After: 
Capture d’écran 2024-02-29 à 17 33 04

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2618/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13969/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2618/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13977/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2618/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13978/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2618/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2618/storybook

**Review by jeremie-lucca — APPROVED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13996/ui-diff)

**Pull request merged**
