### PR TITLE
[ActionIcon] Replace components & documentation references by button

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Replace components & documentation references by button

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2545/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12611/ui-diff)

**Review by martincadoux — APPROVED** [review]
Trop bien, merci ! 🙏

**Review by vvalentin-lucca — DISMISSED** [review]

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12616/ui-diff)

**Review by vvalentin-lucca — APPROVED** [review]

**Review by vvalentin-lucca — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2545/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/12617/ui-diff)

**Review by vvalentin-lucca — APPROVED** [review]

**Review by vvalentin-lucca — APPROVED** [review]

**Pull request merged**
