### PR TITLE
LF 18.2

### PR DESCRIPTION
**Pull request by jeremie-lucca**
#### Table sorted import
```
@forward '@lucca-front/scss/src/components/indexTableSorted';
@forward '@lucca-front/scss/src/components/tableSorted';
```
must be replaced by
```
@forward '@lucca-front/scss/src/components/tableSortable';
```

#### Users
`userTileStyle` mixin import was removed by default to save weight and replaced by a SCSS component. We suggest to replace the mixin import by importing User Tile component (Angular or HTML (🚧 Add link)) or fix it with the deprecated import:
```
@use "@lucca-front/ng/src/definitions/user/user-tile";
```
`userPictureStyle` & `userPictureVars` mixins import were removed for the same reason. We suggest to replace mixins import by importing Avatar (HTML) / User Picture (Angular) (🚧 Add link) component or fix it with the deprecated import:
```
@use "@lucca-front/ng/src/definitions/user/user-picture";
```

#### Select optionKey
On all classes that extend `ALuCoreSelectApiDirective`, apps have to apps have to implement `optionKey` method:
```
class MyDirective extends ALuCoreSelectApiDirective {
	protected override optionKey = (option: T) => option.id;
}
```

#### Divider UI spacings
Divider vertical spacing was reduced from `1.5rem` to `0.25rem` to fit with Figma component.
We suggest to edit margins on divider's surrounding components, but if you need to quickly upgrade, it's possible to override divider margin to avoid UI breakings: 
```
:root {
	--components-divider-margin: var(--pr-t-spacings-300);
}
```

### 🤖 Schematics
- [Empty state] Remplace `title` input by `heading` to avoid browsers native interpretation https://github.com/LuccaSA/lucca-front/pull/2955

### 🎉 Features
- [Phone number] New Angular component https://github.com/LuccaSA/lucca-front/pull/3022
- [Multi language] New Angular component https://github.com/LuccaSA/lucca-front/pull/2890
- [PLG push] New Angular & HTML component https://github.com/LuccaSA/lucca-front/pull/2911
- [Number format] New Angular component to format values & units https://github.com/LuccaSA/lucca-front/pull/2847
- [View tabs] New HTML component https://github.com/LuccaSA/lucca-front/pull/2498
- [Timepicker] Supports AM/PM display depending on `LOCALE_ID` https://github.com/LuccaSA/lucca-front/pull/2888
- [Popover (New)] Supports `hover` + `focus` trigger https://github.com/LuccaSA/lucca-front/pull/2895
- [Table sorted] New HTML sub-component dedicated to Table & Index table  https://github.com/LuccaSA/lucca-front/pull/2858
- [Inline message] Supports `portalContent` https://github.com/LuccaSA/lucca-front/pull/2947
- [Dialog] Supports dialogs opening through routes https://github.com/LuccaSA/lucca-front/pull/2901
- [Tooltip] Add option to prevent screen readers restitution if not needed https://github.com/LuccaSA/lucca-front/pull/2974
- [Page header] Supports "back" button https://github.com/LuccaSA/lucca-front/pull/2948
- [Icons] Add `Medical`, `Arrow line bottom` & `Arrow line top` icons https://github.com/LuccaSA/lucca-front/pull/2975

### 🎨 Visual changes
- [User tile] Title and description positions were inverted and padding was removed to fit with Figma https://github.com/LuccaSA/lucca-front/pull/2940 
- [Toasts] Improve toasts positioning when the page contains a footer https://github.com/LuccaSA/lucca-front/pull/2916
	- Note: It currently only works on basic footer usage. Extra work will be required to cover responsive & footers with custom height.
- [Colors] Replace `neutral 600` by `neutral 700` on textfields and apply disabled variable on a bunch of components https://github.com/LuccaSA/lucca-front/pull/2966
- [Dialogs] Fix footer clipping on Safari https://github.com/LuccaSA/lucca-front/pull/2933 
- [Status badge] Fix vertical alignment in Table https://github.com/LuccaSA/lucca-front/pull/2986
- [Divider] Reduce margin and switch icon color from `neutral 500` to `neutral 600` https://github.com/LuccaSA/lucca-front/pull/3018

### 🚑 Fixes
- [Popover (New)] Resize component after content changed https://github.com/LuccaSA/lucca-front/pull/2991
- [Index table] Improve links to cover right/middle click https://github.com/LuccaSA/lucca-front/pull/2838
- [Simple & Multi select] 💥 `optionKey` is mandatory on `ApiDirectives` https://github.com/LuccaSA/lucca-front/pull/2950
- [Date] Date adapter should not be overridden https://github.com/LuccaSA/lucca-front/pull/2971
- [Tooltip] Prevent Safari native tooltip when text is ellipsed https://github.com/LuccaSA/lucca-front/pull/2958
- [Simple & Multi select] Fix former employees query https://github.com/LuccaSA/lucca-front/pull/2997

### 💬 Translations
- [Translations] Global translation review and improvements https://github.com/LuccaSA/lucca-front/pull/2973

### 🔨 Technical
- [User picture / Avatar] refactor style and support HTML component https://github.com/LuccaSA/lucca-front/pull/3015
- [Checkbox & Radio] Use `grid` display on triggers to avoid `absolute` positioning https://github.com/LuccaSA/lucca-front/pull/2935
- [Colors] Add `0` value to palettes https://github.com/LuccaSA/lucca-front/pull/2921
- [Empty states] Replace `title` input by `heading` to avoid browsers native interpretation https://github.com/LuccaSA/lucca-front/pull/2946

### 📖 Documentation
- [Radio] Add technical documentation https://github.com/LuccaSA/lucca-front/pull/2922

#### Colors variables
- `--colors-white-color` / `--colors-black-color` colors https://github.com/LuccaSA/lucca-front/pull/2921
- `--colors-white-color` must be replaced by `--palettes-neutral-0` or `--pr-t-elevation-surface-raised` depending if color refer to a surface or not.
- `--colors-black-color` must be replaced by `--palettes-neutral-900`.
#### Table 
- `.columnSticky` is replaced by `.stickyColumn` (duplicate) https://github.com/LuccaSA/lucca-front/pull/2928
- `.table-head-row-cell-sortableButton`, `.indexTable-head-row-cell-sortableButton`, `.table-head-row-cell.mod-sortable`, `.table-head-row-cell.sortedAscending` & `.table-head-row-cell.sortedDescending` are replaced by a single tableSortable sub-component for Table and Index Table.
#### Users 
- User tile Mixin `userTileStyle` is replaced by HTML component import: `@forward '@lucca-front/scss/src/components/userTile';`
- User picture / Avatar Mixin `userPictureStyle` & `userPictureVars` are replaced by HTML component import: `@forward '@lucca-front/scss/src/components/userTile';`
#### Utilities 
- `.u-textLeft`, `.u-textCenter` & `.u-textRight` are deprecated and replaced by `.u-textAlignLeft`, `.u-textAlignCenter` & `.u-textAlignRight` for consistency.

[All information related to deprecated elements](https://prisme.lucca.io/94310e217/p/40c515-elements-deprecies)

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2998/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21451/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2998/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21506/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2998/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21551/ui-diff)

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2998/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21604/ui-diff)

**Review by vvalentin-lucca — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2998/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/21933/ui-diff)

**Pull request merged**
