### PR TITLE
LF 15.1

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

-----

### :tada: Features

- :boom: Refactor global sizing nomenclature in order to harmonize with Figma #1975
  - Schematics are provided to avoid most of breakings #1988 
- [Toast] Add title feature + UI improvements #1971 
- [Link] Add external link option + fix default color  #1936 
- [Skiplinks] Is now an Angular component with his own style + minor improvements #1934 
- [Icons] Add home (filled / stared) icons #2000 

### :art: Visual changes
- [Label] Harmonize with Figma #1937
  - 💥 Labels don't have horizontal margin anymore, you may need to manage them for a list of labels.
- [Popup / Modal / Sidepanel] Improve animations #1995 
- [Modal] Minor UI improvements #1935 
- [Tooltip] Minor UI improvements #1991

### 🐞 Fixes
- [Utilities] Fix line through #1948 
- [Sidepanel] Fix overflow issues #1966 
- [Date] Fix issue that prevented users from entering a date with month/year format by keyboard input #1968 
- [Establishment] Fix pagination issues #1970 
- [Tooltip] Fix module imports #1955 

### :hammer: Technical
- We can now override the behaviour of @at-root for CSS components to improve customization options  #1963 
- [Button] Improve CSS vars usage #1931  
- [luUserDisplay] Allow user rendering without having to provide a pipe #1950 
- [Fonts] Now hosted on our CDN #1985 
- Improve page scrolling using scrollbar-gutter property  #1960 
- Fix vulnerabilities #1982 
- Remove Gulp #1976 

-----

### CODE REVIEW

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Review by shajz — APPROVED** [review]
🙈 

👉 I think we could have deprecated the old and functionning class naming system instead of removing it all at once https://github.com/LuccaSA/lucca-front/pull/1975

**Review by shajz — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: http://lucca-front.lucca.local/PR-1992/storybook

**Review by vvalentin-lucca — APPROVED** [review]

**Pull request merged**
