### PR TITLE
[User Select / Qualification][Deprecated] Fix options gap

### PR DESCRIPTION
**Pull request by jeremie-lucca**
## Description

Fix options gap on deprecated user & qualification select

-----

Capture d’écran 2024-02-20 à 18 02 05

-----

### CODE REVIEW

**Review by MarcFairbrother — DISMISSED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2582/storybook

**Comment by CCNET-iLucca** [comment]
[Tests d'interfaces](https://qa.lucca.tech/13520/ui-diff)

**Review by GuillaumeNury — APPROVED** [review]

**Comment by shajz** [comment]
lint issue 
> /packages/ng/qualification/select/input/qualification-select-input.component.html
> error  Replace `·{{·qualification.name·}}·` with `⏎↹↹↹↹{{·qualification.name·}}⏎↹↹↹`  prettier/prettier

(just save it again or run `npm run lint -- --fix`)

**Review by Supamiu — APPROVED** [review]

**Comment by LuccaIntegration** [comment]
:woman_cook: https://lucca-front.lucca.tech/PR-2582/storybook

**Review by MarcFairbrother — APPROVED** [review]

**Pull request merged**
